#include "syscalls.h"

// Define the syscall names array for x86_64
const char *syscall_names_64[] = {
    "read",             // 0
    "write",            // 1
    "open",             // 2
    "close",            // 3
    "stat",             // 4
    "fstat",            // 5
    "lstat",            // 6
    "poll",             // 7
    "pread64",          // 8
    "pwrite64",         // 9
    "lseek",            // 10
    "mmap",             // 11
    "mprotect",         // 12
    "munmap",           // 13
    "brk",              // 14
    "rt_sigaction",     // 15
    "rt_sigprocmask",   // 16
    "rt_sigreturn",     // 17
    "ioctl",            // 18
    "pread64",          // 19
    "pwrite64",         // 20
    "readv",            // 21
    "writev",           // 22
    "access",           // 23
    "pipe",             // 24
    "select",           // 25
    "sched_yield",      // 26
    "mremap",           // 27
    "msync",            // 28
    "mincore",          // 29
    "madvise",          // 30
    "shmget",           // 31
    "shmat",            // 32
    "shmctl",           // 33
    "dup",              // 34
    "dup2",             // 35
    "pause",            // 36
    "nanosleep",        // 37
    "getitimer",        // 38
    "alarm",            // 39
    "setitimer",        // 40
    "getpid",           // 41
    "sendfile",         // 42
    "socket",           // 43
    "connect",          // 44
    "accept",           // 45
    "sendto",           // 46
    "recvfrom",         // 47
    "recvmsg",          // 48
    "sendmsg",          // 49
    "shutdown",         // 50
    "bind",             // 51
    "listen",           // 52
    "getsockname",      // 53
    "getpeername",      // 54
    "socketpair",       // 55
    "setsockopt",       // 56
    "getsockopt",       // 57
    "clone",            // 58
    "fork",             // 59
    "vfork",            // 60
    "execve",           // 61
    "exit",             // 62
    "wait4",            // 63
    "kill",             // 64
    "uname",            // 65
    "semget",           // 66
    "semop",            // 67
    "semctl",           // 68
    "shmdt",            // 69
    "msgget",           // 70
    "msgsnd",           // 71
    "msgrcv",           // 72
    "msgctl",           // 73
    "fcntl",            // 74
    "flock",            // 75
    "fsync",            // 76
    "fdatasync",        // 77
    "truncate",         // 78
    "ftruncate",        // 79
    "getdents",         // 80
    "getcwd",           // 81
    "chdir",            // 82
    "fchdir",           // 83
    "rename",           // 84
    "mkdir",            // 85
    "rmdir",            // 86
    "creat",            // 87
    "link",             // 88
    "unlink",           // 89
    "symlink",          // 90
    "readlink",         // 91
    "chmod",            // 92
    "fchmod",           // 93
    "chown",            // 94
    "fchown",           // 95
    "lchown",           // 96
    "umask",            // 97
    "gettimeofday",     // 98
    "getrlimit",        // 99
    "getrusage",        // 100
    "sysinfo",          // 101
    "times",            // 102
    "ptrace",           // 103
    "getuid",           // 104
    "syslog",           // 105
    "getgid",           // 106
    "setuid",           // 107
    "setgid",           // 108
    "geteuid",          // 109
    "getegid",          // 110
    "setpgid",          // 111
    "getppid",          // 112
    "getpgrp",          // 113
    "setsid",           // 114
    "setreuid",         // 115
    "setregid",         // 116
    "getgroups",        // 117
    "setgroups",        // 118
    "setresuid",        // 119
    "getresuid",        // 120
    "setresgid",        // 121
    "getresgid",        // 122
    "getpgid",          // 123
    "setfsuid",         // 124
    "setfsgid",         // 125
    "getsid",           // 126
    "capget",           // 127
    "capset",           // 128
    "rt_sigpending",    // 129
    "rt_sigtimedwait",  // 130
    "rt_sigqueueinfo",  // 131
    "rt_sigsuspend",    // 132
    "sigaltstack",      // 133
    "utime",            // 134
    "mknod",            // 135
    "uselib",           // 136
    "personality",      // 137
    "ustat",            // 138
    "statfs",           // 139
    "fstatfs",          // 140
    "sysfs",            // 141
    "getpriority",      // 142
    "setpriority",      // 143
    "sched_setparam",   // 144
    "sched_getparam",   // 145
    "sched_setscheduler", // 146
    "sched_getscheduler", // 147
    "sched_get_priority_max", // 148
    "sched_get_priority_min", // 149
    "sched_rr_get_interval", // 150
    "mlock",            // 151
    "munlock",          // 152
    "mlockall",         // 153
    "munlockall",       // 154
    "vhangup",          // 155
    "modify_ldt",       // 156
    "pivot_root",       // 157
    "sysctl",           // 158
    "prctl",            // 159
    "arch_prctl",       // 160
    "adjtimex",         // 161
    "setrlimit",        // 162
    "chroot",           // 163
    "sync",             // 164
    "acct",             // 165
    "settimeofday",     // 166
    "mount",            // 167
    "umount2",          // 168
    "swapon",           // 169
    "swapoff",          // 170
    "reboot",           // 171
    "sethostname",      // 172
    "setdomainname",    // 173
    "iopl",             // 174
    "ioperm",           // 175
    "create_module",    // 176
    "init_module",      // 177
    "delete_module",    // 178
    "get_kernel_syms",  // 179
    "query_module",     // 180
    "quotactl",         // 181
    "nfsservctl",       // 182
    "getpmsg",          // 183
    "putpmsg",          // 184
    "afs_syscall",      // 185
    "tuxcall",          // 186
    "security",         // 187
    "gettid",           // 188
    "readahead",        // 189
    "setxattr",         // 190
    "lsetxattr",        // 191
    "fsetxattr",        // 192
    "getxattr",         // 193
    "lgetxattr",        // 194
    "fgetxattr",        // 195
    "listxattr",        // 196
    "llistxattr",       // 197
    "flistxattr",       // 198
    "removexattr",      // 199
    "lremovexattr",     // 200
    "fremovexattr",     // 201
    "tkill",            // 202
    "time",             // 203
    "futex",            // 204
    "sched_setaffinity", // 205
    "sched_getaffinity", // 206
    "set_thread_area",  // 207
    "io_setup",         // 208
    "io_destroy",       // 209
    "io_getevents",     // 210
    "io_submit",        // 211
    "io_cancel",        // 212
    "get_thread_area",  // 213
    "lookup_dcookie",   // 214
    "epoll_create",     // 215
    "epoll_ctl",        // 216
    "epoll_wait",       // 217
    "remap_file_pages", // 218
    "semtimedop",       // 219
    "rt_sigtimedwait",  // 220
    "fadvise64",        // 221
    "timer_create",     // 222
    "timer_settime",    // 223
    "timer_gettime",    // 224
    "timer_getoverrun", // 225
    "timer_delete",     // 226
    "clock_settime",    // 227
    "clock_gettime",    // 228
    "clock_getres",     // 229
    "clock_nanosleep",  // 230
    "exit_group",       // 231
    "epoll_wait",       // 232
    "epoll_ctl",        // 233
    "tgkill",           // 234
    "utimes",           // 235
    "vserver",          // 236
    "mbind",            // 237
    "set_mempolicy",    // 238
    "get_mempolicy",    // 239
    "mq_open",          // 240
    "mq_unlink",        // 241
    "mq_timedsend",     // 242
    "mq_timedreceive",  // 243
    "mq_notify",        // 244
    "mq_getsetattr",    // 245
    "kexec_load",       // 246
    "waitid",           // 247
    "add_key",          // 248
    "request_key",      // 249
    "keyctl",           // 250
    "ioprio_set",       // 251
    "ioprio_get",       // 252
    "inotify_init",     // 253
    "inotify_add_watch",// 254
    "inotify_rm_watch", // 255
    "migrate_pages",    // 256
    "openat",           // 257
    "mkdirat",          // 258
    "mknodat",          // 259
    "fchownat",         // 260
    "futimesat",        // 261
    "fstatat",          // 262
    "unlinkat",         // 263
    "renameat",         // 264
    "linkat",           // 265
    "symlinkat",        // 266
    "readlinkat",       // 267
    "fchmodat",         // 268
    "faccessat",        // 269
    "pselect6",         // 270
    "ppoll",            // 271
    "unshare",          // 272
    "set_robust_list",  // 273
    "get_robust_list",  // 274
    "splice",           // 275
    "tee",              // 276
    "sync_file_range",  // 277
    "vmsplice",         // 278
    "move_pages",       // 279
    "utimensat",        // 280
    "epoll_pwait",      // 281
    "signalfd",         // 282
    "timerfd",          // 283
    "eventfd",          // 284
    "fallocate",        // 285
    "timerfd_create",   // 286
    "signalfd4",        // 287
    "eventfd2",         // 288
    "epoll_create1",    // 289
    "dup3",             // 290
    "pipe2",            // 291
    "inotify_init1",    // 292
    "preadv",           // 293
    "pwritev",          // 294
    "rt_tgsigqueueinfo",// 295
    "perf_event_open",  // 296
    "fanotify_init",    // 297
    "fanotify_mark",    // 298
    "prlimit64",        // 299
    "name_to_handle_at",// 300
    "open_by_handle_at",// 301
    "clock_adjtime",    // 302
    "syncfs",           // 303
    "sendmmsg",         // 304
    "setns",            // 305
    "getcpu",           // 306
    "process_vm_readv", // 307
    "process_vm_writev",// 308
    "kcmp",             // 309
    "finit_module",     // 310
    "sched_setattr",    // 311
    "sched_getattr",    // 312
    "renameat2",        // 313
    "sekcoompf",        // 314
    "getrandom",        // 315
    "memfd_create",     // 316
    "kexec_file_load",  // 317
    "bpf",              // 318
    "execveat",         // 319
    "socket(AF_INET, SOCK_RAW, 0)", // 320
    "socket(AF_INET, SOCK_DGRAM, 0)", // 321
    "socket(AF_INET, SOCK_STREAM, 0)", // 322
    "socket(AF_INET, SOCK_RDM, 0)", // 323
    "socket(AF_INET6, SOCK_RAW, 0)", // 324
    "socket(AF_INET6, SOCK_DGRAM, 0)", // 325
    "socket(AF_INET6, SOCK_STREAM, 0)", // 326
    "socket(AF_INET6, SOCK_RDM, 0)", // 327
};

// Define the syscall names array for i386 (32-bit)
const char *syscall_names_32[] = {
    "restart_syscall", // 0
    "exit",            // 1
    "fork",            // 2
    "read",            // 3
    "write",           // 4
    "open",            // 5
    "close",           // 6
    "waitpid",         // 7
    "creat",           // 8
    "link",            // 9
    "unlink",          // 10
    "execve",          // 11
    "chdir",           // 12
    "fchdir",          // 13
    "mknod",           // 14
    "chmod",           // 15
    "chown",           // 16
    "lseek",           // 17
    "getpid",          // 18
    "mount",           // 19
    "umount",          // 20
    "setuid",          // 21
    "getuid",          // 22
    "stime",           // 23
    "ptrace",          // 24
    "alarm",           // 25
    "fstat",           // 26
    "pause",           // 27
    "utime",           // 28
    "stty",            // 29
    "gtty",            // 30
    "access",          // 31
    "nice",            // 32
    "sync",            // 33
    "kill",            // 34
    "rename",          // 35
    "mkdir",           // 36
    "rmdir",           // 37
    "dup",             // 38
    "pipe",            // 39
    "times",           // 40
    "prof",            // 41
    "brk",             // 42
    "setgid",          // 43
    "getgid",          // 44
    "signal",          // 45
    "geteuid",         // 46
    "getegid",         // 47
    "acct",            // 48
    "umount2",         // 49
    "lock",            // 50
    "ioctl",           // 51
    "fcntl",           // 52
    "mpx",             // 53
    "setpgid",         // 54
    "ulimit",          // 55
    "uname",           // 56
    "sysinfo",         // 57
    "times",           // 58
    "ptrace",          // 59
    "getuid",          // 60
    "getgid",          // 61
    "geteuid",         // 62
    "getegid",         // 63
    "setpgid",         // 64
    "getppid",         // 65
    "getpgrp",         // 66
    "setsid",          // 67
    "setgroups",       // 68
    "setresuid",       // 69
    "getresuid",       // 70
    "setresgid",       // 71
    "getresgid",       // 72
    "getpgid",         // 73
    "setfsuid",        // 74
    "setfsgid",        // 75
    "getsid",          // 76
    "capget",          // 77
    "capset",          // 78
    "rt_sigpending",   // 79
    "rt_sigtimedwait", // 80
    "rt_sigqueueinfo", // 81
    "rt_sigsuspend",   // 82
    "sigaltstack",     // 83
    "utime",           // 84
    "mknod",           // 85
    "uselib",          // 86
    "personality",     // 87
    "ustat",           // 88
    "statfs",          // 89
    "fstatfs",         // 90
    "sysfs",           // 91
    "getpriority",     // 92
    "setpriority",     // 93
    "sched_setparam",  // 94
    "sched_getparam",  // 95
    "sched_setscheduler", // 96
    "sched_getscheduler", // 97
    "sched_get_priority_max", // 98
    "sched_get_priority_min", // 99
    "sched_rr_get_interval", // 100
    "mlock",           // 101
    "munlock",         // 102
    "mlockall",        // 103
    "munlockall",      // 104
    "vhangup",         // 105
    "modify_ldt",      // 106
    "pivot_root",      // 107
    "sysctl",          // 108
    "prctl",           // 109
    "arch_prctl",      // 110
    "adjtimex",        // 111
    "setrlimit",       // 112
    "chroot",          // 113
    "sync",            // 114
    "acct",            // 115
    "settimeofday",    // 116
    "mount",           // 117
    "umount2",         // 118
    "swapon",          // 119
    "swapoff",         // 120
    "reboot",          // 121
    "sethostname",     // 122
    "setdomainname",   // 123
    "iopl",            // 124
    "ioperm",          // 125
    "create_module",   // 126
    "init_module",     // 127
    "delete_module",   // 128
    "get_kernel_syms", // 129
    "query_module",    // 130
    "quotactl",        // 131
    "nfsservctl",      // 132
    "getpmsg",         // 133
    "putpmsg",         // 134
    "afs_syscall",     // 135
    "tuxcall",         // 136
    "security",        // 137
    "gettid",          // 138
    "readahead",       // 139
    "setxattr",        // 140
    "lsetxattr",       // 141
    "fsetxattr",       // 142
    "getxattr",        // 143
    "lgetxattr",       // 144
    "fgetxattr",       // 145
    "listxattr",       // 146
    "llistxattr",      // 147
    "flistxattr",      // 148
    "removexattr",     // 149
    "lremovexattr",    // 150
    "fremovexattr",    // 151
    "tkill",           // 152
    "time",            // 153
    "futex",           // 154
    "sched_setaffinity", // 155
    "sched_getaffinity", // 156
    "set_thread_area", // 157
    "io_setup",        // 158
    "io_destroy",      // 159
    "io_getevents",    // 160
    "io_submit",       // 161
    "io_cancel",       // 162
    "get_thread_area", // 163
    "lookup_dcookie",  // 164
    "epoll_create",    // 165
    "epoll_ctl",       // 166
    "epoll_wait",      // 167
    "remap_file_pages",// 168
    "semtimedop",      // 169
    "rt_sigtimedwait", // 170
    "fadvise64",       // 171
    "timer_create",    // 172
    "timer_settime",   // 173
    "timer_gettime",   // 174
    "timer_getoverrun",// 175
    "timer_delete",    // 176
    "clock_settime",   // 177
    "clock_gettime",   // 178
    "clock_getres",    // 179
    "clock_nanosleep", // 180
    "exit_group",      // 181
    "epoll_wait",      // 182
    "epoll_ctl",       // 183
    "tgkill",          // 184
    "utimes",          // 185
    "vserver",         // 186
    "mbind",           // 187
    "set_mempolicy",   // 188
    "get_mempolicy",   // 189
    "mq_open",         // 190
    "mq_unlink",       // 191
    "mq_timedsend",    // 192
    "mq_timedreceive", // 193
    "mq_notify",       // 194
    "mq_getsetattr",   // 195
    "kexec_load",      // 196
    "waitid",          // 197
    "add_key",         // 198
    "request_key",     // 199
    "keyctl",          // 200
    "ioprio_set",      // 201
    "ioprio_get",      // 202
    "inotify_init",    // 203
    "inotify_add_watch", // 204
    "inotify_rm_watch",  // 205
    "migrate_pages",   // 206
    "openat",          // 207
    "mkdirat",         // 208
    "mknodat",         // 209
    "fchownat",        // 210
    "futimesat",       // 211
    "fstatat",         // 212
    "unlinkat",        // 213
    "renameat",        // 214
    "linkat",          // 215
    "symlinkat",       // 216
    "readlinkat",      // 217
    "fchmodat",        // 218
    "faccessat",       // 219
    "pselect6",        // 220
    "ppoll",           // 221
    "unshare",         // 222
    "set_robust_list", // 223
    "get_robust_list", // 224
    "splice",          // 225
    "tee",             // 226
    "sync_file_range", // 227
    "vmsplice",        // 228
    "move_pages",      // 229
    "utimensat",       // 230
    "epoll_pwait",     // 231
    "signalfd",        // 232
    "timerfd",         // 233
    "eventfd",         // 234
    "fallocate",       // 235
    "timerfd_create",  // 236
    "signalfd4",       // 237
    "eventfd2",        // 238
    "epoll_create1",   // 239
    "dup3",            // 240
    "pipe2",           // 241
    "inotify_init1",   // 242
    "preadv",          // 243
    "pwritev",         // 244
    "rt_tgsigqueueinfo", // 245
    "perf_event_open", // 246
    "fanotify_init",   // 247
    "fanotify_mark",   // 248
    "prlimit64",       // 249
    "name_to_handle_at", // 250
    "open_by_handle_at", // 251
    "clock_adjtime",   // 252
    "syncfs",          // 253
    "sendmmsg",        // 254
    "setns",           // 255
    "getcpu",          // 256
    "process_vm_readv", // 257
    "process_vm_writev", // 258
    "kcmp",            // 259
    "finit_module",    // 260
    "sched_setattr",   // 261
    "sched_getattr",   // 262
    "renameat2",       // 263
    "sekcoompf",       // 264
    "getrandom",       // 265
    "memfd_create",    // 266
    "kexec_file_load", // 267
    "bpf",             // 268
    "execveat",        // 269
    "socket(AF_INET, SOCK_RAW, 0)", // 270
    "socket(AF_INET, SOCK_DGRAM, 0)", // 271
    "socket(AF_INET, SOCK_STREAM, 0)", // 272
    "socket(AF_INET, SOCK_RDM, 0)", // 273
    "socket(AF_INET6, SOCK_RAW, 0)", // 274
    "socket(AF_INET6, SOCK_DGRAM, 0)", // 275
    "socket(AF_INET6, SOCK_STREAM, 0)", // 276
    "socket(AF_INET6, SOCK_RDM, 0)", // 277
};
