#ifndef SYSCALLS_H
#define SYSCALLS_H

#include <stddef.h>

// Define the number of syscalls
#define SYSCALL_COUNT 332

/* Normally, MAX_PARAMS is always 6 */
# define MAX_PARAMS	6

/**
 * enum type_e - Enumerates the different types present in the different
 * syscall parameters and return types
 */
typedef enum type_e
{
	AIO_CONTEXT_T,
	AIO_CONTEXT_T_P,
	CADDR_T,
	CAP_USER_DATA_T,
	CAP_USER_HEADER_T,
	CHAR_P,
	CHAR_PP,
	CLOCKID_T,
	CLOCK_T,
	CPU_SET_T_P,
	DEV_T,
	ENUM___PTRACE_REQUEST,
	FD_SET_P,
	GID_T,
	GID_T_P,
	IDTYPE_T,
	ID_T,
	INT,
	INT_P,
	KEY_SERIAL_T,
	KEY_T,
	LOFF_T_P,
	LONG,
	LONG_P,
	MODE_T,
	MQD_T,
	NFDS_T,
	OFF64_T,
	OFF_T,
	OFF_T_P,
	PID_T,
	SIGHANDLER_T,
	SIGINFO_T_P,
	SIGSET_T_P,
	SIZE_T,
	SIZE_T_P,
	SOCKLEN_T,
	SOCKLEN_T_P,
	SSIZE_T,
	STACK_T_P,
	STRUCT_EPOLL_EVENT_P,
	STRUCT_GETCPU_CACHE_P,
	STRUCT_IOCB_P,
	STRUCT_IOCB_PP,
	STRUCT_IOVEC_P,
	STRUCT_IO_EVENT_P,
	STRUCT_ITIMERSPEC_P,
	STRUCT_ITIMERVAL_P,
	STRUCT_KERNEL_SYM_P,
	STRUCT_KEXEC_SEGMENT_P,
	STRUCT_LINUX_DIRENT_P,
	STRUCT_MMSGHDR_P,
	STRUCT_MQ_ATTR_P,
	STRUCT_MSGHDR_P,
	STRUCT_MSQID_DS_P,
	STRUCT_NFSCTL_ARG_P,
	STRUCT_OLD_LINUX_DIRENT_P,
	STRUCT_PERF_EVENT_ATTR_P,
	STRUCT_POLLFD_P,
	STRUCT_RLIMIT_P,
	STRUCT_ROBUST_LIST_HEAD_P,
	STRUCT_ROBUST_LIST_HEAD_PP,
	STRUCT_RUSAGE_P,
	STRUCT_SCHED_PARAM_P,
	STRUCT_SEMBUF_P,
	STRUCT_SHMID_DS_P,
	STRUCT_SIGACTION_P,
	STRUCT_SIGEVENT_P,
	STRUCT_SOCKADDR_P,
	STRUCT_STATFS_P,
	STRUCT_STAT_P,
	STRUCT_SYSINFO_P,
	STRUCT_TIMESPEC_P,
	STRUCT_TIMEVAL_P,
	STRUCT_TIMEX_P,
	STRUCT_TIMEZONE_P,
	STRUCT_TMS_P,
	STRUCT_USER_DESC_P,
	STRUCT_USTAT_P,
	STRUCT_UTIMBUF_P,
	STRUCT_UTSNAME_P,
	STRUCT_VM86_STRUCT_P,
	STRUCT___SYSCTL_ARGS_P,
	TIMER_T,
	TIMER_T_P,
	TIME_T,
	TIME_T_P,
	U64,
	UID_T,
	UID_T_P,
	UINT32_T,
	UNION_NFSCTL_RES_P,
	UNSIGNED_CHAR_P,
	UNSIGNED_INT,
	UNSIGNED_INT_P,
	UNSIGNED_LONG,
	UNSIGNED_LONG_P,
	VARARGS,
	VOID,
	VOID_P,
	VOID_PP
} type_t;

/**
 * struct syscall_s - Stores information about a syscall
 *
 * @name: Name of the syscall
 * @nr: Syscall number in the syscalls table
 * @ret: Return type
 * @nb_params: Number of parameters
 * @params: Array of parameters types
 */
typedef struct syscall_s
{
	char const * const name;
	size_t const nr;
	type_t const ret;
	size_t const nb_params;
	type_t const params[MAX_PARAMS];
} syscall_t;

static syscall_t const syscalls_64_g[] = {
	{"read", 0, SSIZE_T, 3, {INT, VOID_P, SIZE_T, -1, -1, -1}},
	{"write", 1, SSIZE_T, 3, {INT, VOID_P, SIZE_T, -1, -1, -1}},
	{"open", 2, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"close", 3, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"stat", 4, INT, 2, {CHAR_P, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"fstat", 5, INT, 2, {INT, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"lstat", 6, INT, 2, {CHAR_P, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"poll", 7, INT, 3, {STRUCT_POLLFD_P, NFDS_T, INT, -1, -1, -1}},
	{"lseek", 8, OFF_T, 3, {INT, OFF_T, INT, -1, -1, -1}},
	{"mmap", 9, VOID_P, 6, {VOID_P, SIZE_T, INT, INT, INT, OFF_T}},
	{"mprotect", 10, INT, 3, {VOID_P, SIZE_T, INT, -1, -1, -1}},
	{"munmap", 11, INT, 2, {VOID_P, SIZE_T, -1, -1, -1, -1}},
	{"brk", 12, INT, 1, {VOID_P, -1, -1, -1, -1, -1}},
	{"rt_sigaction", 13, INT, 3, {INT, STRUCT_SIGACTION_P,
		STRUCT_SIGACTION_P, -1, -1, -1}},
	{"rt_sigprocmask", 14, INT, 3, {INT, SIGSET_T_P, SIGSET_T_P, -1, -1,
		-1}},
	{"rt_sigreturn", 15, INT, 1, {UNSIGNED_LONG, -1, -1, -1, -1, -1}},
	{"ioctl", 16, INT, 3, {INT, INT, VARARGS, -1, -1, -1}},
	{"pread64", 17, SSIZE_T, 4, {INT, VOID_P, SIZE_T, OFF_T, -1, -1}},
	{"pwrite64", 18, SSIZE_T, 4, {INT, VOID_P, SIZE_T, OFF_T, -1, -1}},
	{"readv", 19, SSIZE_T, 3, {INT, STRUCT_IOVEC_P, INT, -1, -1, -1}},
	{"writev", 20, SSIZE_T, 3, {INT, STRUCT_IOVEC_P, INT, -1, -1, -1}},
	{"access", 21, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"pipe", 22, INT, 1, {INT_P, -1, -1, -1, -1, -1}},
	{"select", 23, INT, 5, {INT, FD_SET_P, FD_SET_P, FD_SET_P,
		STRUCT_TIMEVAL_P, -1}},
	{"sched_yield", 24, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"mremap", 25, VOID_P, 5, {VOID_P, SIZE_T, SIZE_T, INT, VARARGS, -1}},
	{"msync", 26, INT, 3, {VOID_P, SIZE_T, INT, -1, -1, -1}},
	{"mincore", 27, INT, 3, {VOID_P, SIZE_T, UNSIGNED_CHAR_P, -1, -1, -1}},
	{"madvise", 28, INT, 3, {VOID_P, SIZE_T, INT, -1, -1, -1}},
	{"shmget", 29, INT, 3, {KEY_T, SIZE_T, INT, -1, -1, -1}},
	{"shmat", 30, VOID_P, 3, {INT, VOID_P, INT, -1, -1, -1}},
	{"shmctl", 31, INT, 3, {INT, INT, STRUCT_SHMID_DS_P, -1, -1, -1}},
	{"dup", 32, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"dup2", 33, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"pause", 34, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"nanosleep", 35, INT, 2, {STRUCT_TIMESPEC_P, STRUCT_TIMESPEC_P, -1,
		-1, -1, -1}},
	{"getitimer", 36, INT, 2, {INT, STRUCT_ITIMERVAL_P, -1, -1, -1, -1}},
	{"alarm", 37, UNSIGNED_INT, 1, {UNSIGNED_INT, -1, -1, -1, -1, -1}},
	{"setitimer", 38, INT, 3, {INT, STRUCT_ITIMERVAL_P, STRUCT_ITIMERVAL_P,
		-1, -1, -1}},
	{"getpid", 39, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"sendfile", 40, SSIZE_T, 4, {INT, INT, OFF_T_P, SIZE_T, -1, -1}},
	{"socket", 41, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"connect", 42, INT, 3, {INT, STRUCT_SOCKADDR_P, SOCKLEN_T, -1, -1,
		-1}},
	{"accept", 43, INT, 3, {INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, -1, -1,
		-1}},
	{"sendto", 44, SSIZE_T, 6, {INT, VOID_P, SIZE_T, INT,
		STRUCT_SOCKADDR_P, SOCKLEN_T}},
	{"recvfrom", 45, SSIZE_T, 6, {INT, VOID_P, SIZE_T, INT,
		STRUCT_SOCKADDR_P, SOCKLEN_T_P}},
	{"sendmsg", 46, SSIZE_T, 3, {INT, STRUCT_MSGHDR_P, INT, -1, -1, -1}},
	{"recvmsg", 47, SSIZE_T, 3, {INT, STRUCT_MSGHDR_P, INT, -1, -1, -1}},
	{"shutdown", 48, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"bind", 49, INT, 3, {INT, STRUCT_SOCKADDR_P, SOCKLEN_T, -1, -1, -1}},
	{"listen", 50, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"getsockname", 51, INT, 3, {INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, -1,
		-1, -1}},
	{"getpeername", 52, INT, 3, {INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, -1,
		-1, -1}},
	{"socketpair", 53, INT, 4, {INT, INT, INT, INT_P, -1, -1}},
	{"setsockopt", 54, INT, 5, {INT, INT, INT, VOID_P, SOCKLEN_T, -1}},
	{"getsockopt", 55, INT, 5, {INT, INT, INT, VOID_P, SOCKLEN_T_P, -1}},
	{"clone", 56, INT, 5, {INT, VOID_P, INT, VOID_P, VARARGS, -1}},
	{"fork", 57, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"vfork", 58, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"execve", 59, INT, 3, {CHAR_P, CHAR_PP, CHAR_PP, -1, -1, -1}},
	{"exit", 60, VOID, 1, {INT, -1, -1, -1, -1, -1}},
	{"wait4", 61, PID_T, 4, {PID_T, INT_P, INT, STRUCT_RUSAGE_P, -1, -1}},
	{"kill", 62, INT, 2, {PID_T, INT, -1, -1, -1, -1}},
	{"uname", 63, INT, 1, {STRUCT_UTSNAME_P, -1, -1, -1, -1, -1}},
	{"semget", 64, INT, 3, {KEY_T, INT, INT, -1, -1, -1}},
	{"semop", 65, INT, 3, {INT, STRUCT_SEMBUF_P, UNSIGNED_INT, -1, -1, -1}},
	{"semctl", 66, INT, 4, {INT, INT, INT, VARARGS, -1, -1}},
	{"shmdt", 67, INT, 1, {VOID_P, -1, -1, -1, -1, -1}},
	{"msgget", 68, INT, 2, {KEY_T, INT, -1, -1, -1, -1}},
	{"msgsnd", 69, INT, 4, {INT, VOID_P, SIZE_T, INT, -1, -1}},
	{"msgrcv", 70, SSIZE_T, 5, {INT, VOID_P, SIZE_T, LONG, INT, -1}},
	{"msgctl", 71, INT, 3, {INT, INT, STRUCT_MSQID_DS_P, -1, -1, -1}},
	{"fcntl", 72, INT, 3, {INT, INT, VARARGS, -1, -1, -1}},
	{"flock", 73, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"fsync", 74, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"fdatasync", 75, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"truncate", 76, INT, 2, {CHAR_P, OFF_T, -1, -1, -1, -1}},
	{"ftruncate", 77, INT, 2, {INT, OFF_T, -1, -1, -1, -1}},
	{"getdents", 78, INT, 3, {UNSIGNED_INT, STRUCT_LINUX_DIRENT_P,
		UNSIGNED_INT, -1, -1, -1}},
	{"getcwd", 79, CHAR_P, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"chdir", 80, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"fchdir", 81, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"rename", 82, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"mkdir", 83, INT, 2, {CHAR_P, MODE_T, -1, -1, -1, -1}},
	{"rmdir", 84, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"creat", 85, INT, 2, {CHAR_P, MODE_T, -1, -1, -1, -1}},
	{"link", 86, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"unlink", 87, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"symlink", 88, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"readlink", 89, SSIZE_T, 3, {CHAR_P, CHAR_P, SIZE_T, -1, -1, -1}},
	{"chmod", 90, INT, 2, {CHAR_P, MODE_T, -1, -1, -1, -1}},
	{"fchmod", 91, INT, 2, {INT, MODE_T, -1, -1, -1, -1}},
	{"chown", 92, INT, 3, {CHAR_P, UID_T, GID_T, -1, -1, -1}},
	{"fchown", 93, INT, 3, {INT, UID_T, GID_T, -1, -1, -1}},
	{"lchown", 94, INT, 3, {CHAR_P, UID_T, GID_T, -1, -1, -1}},
	{"umask", 95, MODE_T, 1, {MODE_T, -1, -1, -1, -1, -1}},
	{"gettimeofday", 96, INT, 2, {STRUCT_TIMEVAL_P, STRUCT_TIMEZONE_P, -1,
		-1, -1, -1}},
	{"getrlimit", 97, INT, 2, {INT, STRUCT_RLIMIT_P, -1, -1, -1, -1}},
	{"getrusage", 98, INT, 2, {INT, STRUCT_RUSAGE_P, -1, -1, -1, -1}},
	{"sysinfo", 99, INT, 1, {STRUCT_SYSINFO_P, -1, -1, -1, -1, -1}},
	{"times", 100, CLOCK_T, 1, {STRUCT_TMS_P, -1, -1, -1, -1, -1}},
	{"ptrace", 101, LONG, 4, {ENUM___PTRACE_REQUEST, PID_T, VOID_P,
		VOID_P, -1, -1}},
	{"getuid", 102, UID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"syslog", 103, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"getgid", 104, GID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"setuid", 105, INT, 1, {UID_T, -1, -1, -1, -1, -1}},
	{"setgid", 106, INT, 1, {GID_T, -1, -1, -1, -1, -1}},
	{"geteuid", 107, UID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"getegid", 108, GID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"setpgid", 109, INT, 2, {PID_T, PID_T, -1, -1, -1, -1}},
	{"getppid", 110, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"getpgrp", 111, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"setsid", 112, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"setreuid", 113, INT, 2, {UID_T, UID_T, -1, -1, -1, -1}},
	{"setregid", 114, INT, 2, {GID_T, GID_T, -1, -1, -1, -1}},
	{"getgroups", 115, INT, 2, {INT, GID_T_P, -1, -1, -1, -1}},
	{"setgroups", 116, INT, 2, {SIZE_T, GID_T_P, -1, -1, -1, -1}},
	{"setresuid", 117, INT, 3, {UID_T, UID_T, UID_T, -1, -1, -1}},
	{"getresuid", 118, INT, 3, {UID_T_P, UID_T_P, UID_T_P, -1, -1, -1}},
	{"setresgid", 119, INT, 3, {GID_T, GID_T, GID_T, -1, -1, -1}},
	{"getresgid", 120, INT, 3, {GID_T_P, GID_T_P, GID_T_P, -1, -1, -1}},
	{"getpgid", 121, PID_T, 1, {PID_T, -1, -1, -1, -1, -1}},
	{"setfsuid", 122, INT, 1, {UID_T, -1, -1, -1, -1, -1}},
	{"setfsgid", 123, INT, 1, {UID_T, -1, -1, -1, -1, -1}},
	{"getsid", 124, PID_T, 1, {PID_T, -1, -1, -1, -1, -1}},
	{"capget", 125, INT, 2, {CAP_USER_HEADER_T, CAP_USER_DATA_T, -1, -1,
		-1, -1}},
	{"capset", 126, INT, 2, {CAP_USER_HEADER_T, CAP_USER_DATA_T, -1, -1,
		-1, -1}},
	{"rt_sigpending", 127, INT, 1, {SIGSET_T_P, -1, -1, -1, -1, -1}},
	{"rt_sigtimedwait", 128, INT, 3, {SIGSET_T_P, SIGINFO_T_P,
		STRUCT_TIMESPEC_P, -1, -1, -1}},
	{"rt_sigqueueinfo", 129, INT, 3, {PID_T, INT, SIGINFO_T_P, -1, -1, -1}},
	{"rt_sigsuspend", 130, INT, 1, {SIGSET_T_P, -1, -1, -1, -1, -1}},
	{"sigaltstack", 131, INT, 2, {STACK_T_P, STACK_T_P, -1, -1, -1, -1}},
	{"utime", 132, INT, 2, {CHAR_P, STRUCT_UTIMBUF_P, -1, -1, -1, -1}},
	{"mknod", 133, INT, 3, {CHAR_P, MODE_T, DEV_T, -1, -1, -1}},
	{"uselib", 134, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"personality", 135, INT, 1, {UNSIGNED_LONG, -1, -1, -1, -1, -1}},
	{"ustat", 136, INT, 2, {DEV_T, STRUCT_USTAT_P, -1, -1, -1, -1}},
	{"statfs", 137, INT, 2, {CHAR_P, STRUCT_STATFS_P, -1, -1, -1, -1}},
	{"fstatfs", 138, INT, 2, {INT, STRUCT_STATFS_P, -1, -1, -1, -1}},
	{"sysfs", 139, INT, 2, {INT, CHAR_P, -1, -1, -1, -1}},
	{"getpriority", 140, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"setpriority", 141, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"sched_setparam", 142, INT, 2, {PID_T, STRUCT_SCHED_PARAM_P, -1, -1,
		-1, -1}},
	{"sched_getparam", 143, INT, 2, {PID_T, STRUCT_SCHED_PARAM_P, -1, -1,
		-1, -1}},
	{"sched_setscheduler", 144, INT, 3, {PID_T, INT, STRUCT_SCHED_PARAM_P,
		-1, -1, -1}},
	{"sched_getscheduler", 145, INT, 1, {PID_T, -1, -1, -1, -1, -1}},
	{"sched_get_priority_max", 146, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"sched_get_priority_min", 147, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"sched_rr_get_interval", 148, INT, 2, {PID_T, STRUCT_TIMESPEC_P, -1,
		-1, -1, -1}},
	{"mlock", 149, INT, 2, {VOID_P, SIZE_T, -1, -1, -1, -1}},
	{"munlock", 150, INT, 2, {VOID_P, SIZE_T, -1, -1, -1, -1}},
	{"mlockall", 151, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"munlockall", 152, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"vhangup", 153, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"modify_ldt", 154, INT, 3, {INT, VOID_P, UNSIGNED_LONG, -1, -1, -1}},
	{"pivot_root", 155, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"_sysctl", 156, INT, 1, {STRUCT___SYSCTL_ARGS_P, -1, -1, -1, -1, -1}},
	{"prctl", 157, INT, 5, {INT, UNSIGNED_LONG, UNSIGNED_LONG,
		UNSIGNED_LONG, UNSIGNED_LONG, -1}},
	{"arch_prctl", 158, INT, 2, {INT, UNSIGNED_LONG, -1, -1, -1, -1}},
	{"adjtimex", 159, INT, 1, {STRUCT_TIMEX_P, -1, -1, -1, -1, -1}},
	{"setrlimit", 160, INT, 2, {INT, STRUCT_RLIMIT_P, -1, -1, -1, -1}},
	{"chroot", 161, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"sync", 162, VOID, 1, {VOID, -1, -1, -1, -1, -1}},
	{"acct", 163, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"settimeofday", 164, INT, 2, {STRUCT_TIMEVAL_P, STRUCT_TIMEZONE_P,
		-1, -1, -1, -1}},
	{"mount", 165, INT, 5, {CHAR_P, CHAR_P, CHAR_P, UNSIGNED_LONG, VOID_P,
		-1}},
	{"umount2", 166, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"swapon", 167, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"swapoff", 168, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"reboot", 169, INT, 4, {INT, INT, INT, VOID_P, -1, -1}},
	{"sethostname", 170, INT, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"setdomainname", 171, INT, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"iopl", 172, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"ioperm", 173, INT, 3, {UNSIGNED_LONG, UNSIGNED_LONG, INT, -1, -1,
		-1}},
	{"create_module", 174, CADDR_T, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"init_module", 175, INT, 3, {VOID_P, UNSIGNED_LONG, CHAR_P, -1, -1,
		-1}},
	{"delete_module", 176, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"get_kernel_syms", 177, INT, 1, {STRUCT_KERNEL_SYM_P, -1, -1, -1, -1,
		-1}},
	{"query_module", 178, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"quotactl", 179, INT, 4, {INT, CHAR_P, INT, CADDR_T, -1, -1}},
	{"nfsservctl", 180, LONG, 3, {INT, STRUCT_NFSCTL_ARG_P,
		UNION_NFSCTL_RES_P, -1, -1, -1}},
	{"getpmsg", 181, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"putpmsg", 182, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"afs_syscall", 183, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"tuxcall", 184, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"security", 185, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"gettid", 186, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"readahead", 187, SSIZE_T, 3, {INT, OFF64_T, SIZE_T, -1, -1, -1}},
	{"setxattr", 188, INT, 5, {CHAR_P, CHAR_P, VOID_P, SIZE_T, INT, -1}},
	{"lsetxattr", 189, INT, 5, {CHAR_P, CHAR_P, VOID_P, SIZE_T, INT, -1}},
	{"fsetxattr", 190, INT, 5, {INT, CHAR_P, VOID_P, SIZE_T, INT, -1}},
	{"getxattr", 191, SSIZE_T, 4, {CHAR_P, CHAR_P, VOID_P, SIZE_T, -1, -1}},
	{"lgetxattr", 192, SSIZE_T, 4, {CHAR_P, CHAR_P, VOID_P, SIZE_T, -1,
		-1}},
	{"fgetxattr", 193, SSIZE_T, 4, {INT, CHAR_P, VOID_P, SIZE_T, -1, -1}},
	{"listxattr", 194, SSIZE_T, 3, {CHAR_P, CHAR_P, SIZE_T, -1, -1, -1}},
	{"llistxattr", 195, SSIZE_T, 3, {CHAR_P, CHAR_P, SIZE_T, -1, -1, -1}},
	{"flistxattr", 196, SSIZE_T, 3, {INT, CHAR_P, SIZE_T, -1, -1, -1}},
	{"removexattr", 197, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"lremovexattr", 198, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"fremovexattr", 199, INT, 2, {INT, CHAR_P, -1, -1, -1, -1}},
	{"tkill", 200, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"time", 201, TIME_T, 1, {TIME_T_P, -1, -1, -1, -1, -1}},
	{"futex", 202, INT, 6, {INT_P, INT, INT, STRUCT_TIMESPEC_P, INT_P,
		INT}},
	{"sched_setaffinity", 203, INT, 3, {PID_T, SIZE_T, CPU_SET_T_P, -1,
		-1, -1}},
	{"sched_getaffinity", 204, INT, 3, {PID_T, SIZE_T, CPU_SET_T_P, -1,
		-1, -1}},
	{"set_thread_area", 205, INT, 1, {STRUCT_USER_DESC_P, -1, -1, -1, -1,
		-1}},
	{"io_setup", 206, INT, 2, {UNSIGNED_INT, AIO_CONTEXT_T_P, -1, -1, -1,
		-1}},
	{"io_destroy", 207, INT, 1, {AIO_CONTEXT_T, -1, -1, -1, -1, -1}},
	{"io_getevents", 208, INT, 5, {AIO_CONTEXT_T, LONG, LONG,
		STRUCT_IO_EVENT_P, STRUCT_TIMESPEC_P, -1}},
	{"io_submit", 209, INT, 3, {AIO_CONTEXT_T, LONG, STRUCT_IOCB_PP, -1,
		-1, -1}},
	{"io_cancel", 210, INT, 3, {AIO_CONTEXT_T, STRUCT_IOCB_P,
		STRUCT_IO_EVENT_P, -1, -1, -1}},
	{"get_thread_area", 211, INT, 1, {STRUCT_USER_DESC_P, -1, -1, -1, -1,
		-1}},
	{"lookup_dcookie", 212, INT, 3, {U64, CHAR_P, SIZE_T, -1, -1, -1}},
	{"epoll_create", 213, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"epoll_ctl_old", 214, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"epoll_wait_old", 215, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"remap_file_pages", 216, INT, 5, {VOID_P, SIZE_T, INT, SSIZE_T, INT,
		-1}},
	{"getdents64", 217, INT, 3, {UNSIGNED_INT, STRUCT_LINUX_DIRENT_P,
		UNSIGNED_INT, -1, -1, -1}},
	{"set_tid_address", 218, LONG, 1, {INT_P, -1, -1, -1, -1, -1}},
	{"restart_syscall", 219, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"semtimedop", 220, INT, 4, {INT, STRUCT_SEMBUF_P, UNSIGNED_INT,
		STRUCT_TIMESPEC_P, -1, -1}},
	{"fadvise64", 221, INT, 4, {INT, OFF_T, OFF_T, INT, -1, -1}},
	{"timer_create", 222, INT, 3, {CLOCKID_T, STRUCT_SIGEVENT_P,
		TIMER_T_P, -1, -1, -1}},
	{"timer_settime", 223, INT, 4, {TIMER_T, INT, STRUCT_ITIMERSPEC_P,
		STRUCT_ITIMERSPEC_P, -1, -1}},
	{"timer_gettime", 224, INT, 2, {TIMER_T, STRUCT_ITIMERSPEC_P, -1, -1,
		-1, -1}},
	{"timer_getoverrun", 225, INT, 1, {TIMER_T, -1, -1, -1, -1, -1}},
	{"timer_delete", 226, INT, 1, {TIMER_T, -1, -1, -1, -1, -1}},
	{"clock_settime", 227, INT, 2, {CLOCKID_T, STRUCT_TIMESPEC_P, -1, -1,
		-1, -1}},
	{"clock_gettime", 228, INT, 2, {CLOCKID_T, STRUCT_TIMESPEC_P, -1, -1,
		-1, -1}},
	{"clock_getres", 229, INT, 2, {CLOCKID_T, STRUCT_TIMESPEC_P, -1, -1,
		-1, -1}},
	{"clock_nanosleep", 230, INT, 4, {CLOCKID_T, INT, STRUCT_TIMESPEC_P,
		STRUCT_TIMESPEC_P, -1, -1}},
	{"exit_group", 231, VOID, 1, {INT, -1, -1, -1, -1, -1}},
	{"epoll_wait", 232, INT, 4, {INT, STRUCT_EPOLL_EVENT_P, INT, INT, -1,
		-1}},
	{"epoll_ctl", 233, INT, 4, {INT, INT, INT, STRUCT_EPOLL_EVENT_P, -1,
		-1}},
	{"tgkill", 234, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"utimes", 235, INT, 2, {CHAR_P, STRUCT_TIMEVAL_P, -1, -1, -1, -1}},
	{"vserver", 236, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"mbind", 237, INT, 6, {VOID_P, UNSIGNED_LONG, INT, UNSIGNED_LONG_P,
		UNSIGNED_LONG, UNSIGNED_INT}},
	{"set_mempolicy", 238, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"get_mempolicy", 239, INT, 5, {INT_P, UNSIGNED_LONG_P, UNSIGNED_LONG,
		UNSIGNED_LONG, UNSIGNED_LONG, -1}},
	{"mq_open", 240, MQD_T, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"mq_unlink", 241, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"mq_timedsend", 242, INT, 5, {MQD_T, CHAR_P, SIZE_T, UNSIGNED_INT,
		STRUCT_TIMESPEC_P, -1}},
	{"mq_timedreceive", 243, SSIZE_T, 5, {MQD_T, CHAR_P, SIZE_T,
		UNSIGNED_INT_P, STRUCT_TIMESPEC_P, -1}},
	{"mq_notify", 244, INT, 2, {MQD_T, STRUCT_SIGEVENT_P, -1, -1, -1, -1}},
	{"mq_getsetattr", 245, INT, 3, {MQD_T, STRUCT_MQ_ATTR_P,
		STRUCT_MQ_ATTR_P, -1, -1, -1}},
	{"kexec_load", 246, LONG, 4, {UNSIGNED_LONG, UNSIGNED_LONG,
		STRUCT_KEXEC_SEGMENT_P, UNSIGNED_LONG, -1, -1}},
	{"waitid", 247, INT, 4, {IDTYPE_T, ID_T, SIGINFO_T_P, INT, -1, -1}},
	{"add_key", 248, KEY_SERIAL_T, 5, {CHAR_P, CHAR_P, VOID_P, SIZE_T,
		KEY_SERIAL_T, -1}},
	{"request_key", 249, KEY_SERIAL_T, 4, {CHAR_P, CHAR_P, CHAR_P,
		KEY_SERIAL_T, -1, -1}},
	{"keyctl", 250, LONG, 2, {INT, VARARGS, -1, -1, -1, -1}},
	{"ioprio_set", 251, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"ioprio_get", 252, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"inotify_init", 253, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"inotify_add_watch", 254, INT, 3, {INT, CHAR_P, UINT32_T, -1, -1, -1}},
	{"inotify_rm_watch", 255, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"migrate_pages", 256, LONG, 4, {INT, UNSIGNED_LONG, UNSIGNED_LONG_P,
		UNSIGNED_LONG_P, -1, -1}},
	{"openat", 257, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"mkdirat", 258, INT, 3, {INT, CHAR_P, MODE_T, -1, -1, -1}},
	{"mknodat", 259, INT, 4, {INT, CHAR_P, MODE_T, DEV_T, -1, -1}},
	{"fchownat", 260, INT, 5, {INT, CHAR_P, UID_T, GID_T, INT, -1}},
	{"futimesat", 261, INT, 3, {INT, CHAR_P, STRUCT_TIMEVAL_P, -1, -1, -1}},
	{"newfstatat", 262, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"unlinkat", 263, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"renameat", 264, INT, 4, {INT, CHAR_P, INT, CHAR_P, -1, -1}},
	{"linkat", 265, INT, 5, {INT, CHAR_P, INT, CHAR_P, INT, -1}},
	{"symlinkat", 266, INT, 3, {CHAR_P, INT, CHAR_P, -1, -1, -1}},
	{"readlinkat", 267, INT, 4, {INT, CHAR_P, CHAR_P, SIZE_T, -1, -1}},
	{"fchmodat", 268, INT, 4, {INT, CHAR_P, MODE_T, INT, -1, -1}},
	{"faccessat", 269, INT, 4, {INT, CHAR_P, INT, INT, -1, -1}},
	{"pselect6", 270, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"ppoll", 271, INT, 4, {STRUCT_POLLFD_P, NFDS_T, STRUCT_TIMESPEC_P,
		SIGSET_T_P, -1, -1}},
	{"unshare", 272, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"set_robust_list", 273, LONG, 2, {STRUCT_ROBUST_LIST_HEAD_P,
		SIZE_T, -1, -1, -1, -1}},
	{"get_robust_list", 274, LONG, 3, {INT, STRUCT_ROBUST_LIST_HEAD_PP,
		SIZE_T_P, -1, -1, -1}},
	{"splice", 275, SSIZE_T, 6, {INT, LOFF_T_P, INT, LOFF_T_P, SIZE_T,
		UNSIGNED_INT}},
	{"tee", 276, SSIZE_T, 4, {INT, INT, SIZE_T, UNSIGNED_INT, -1, -1}},
	{"sync_file_range", 277, INT, 4, {INT, OFF64_T, OFF64_T, UNSIGNED_INT,
		-1, -1}},
	{"vmsplice", 278, SSIZE_T, 4, {INT, STRUCT_IOVEC_P, UNSIGNED_LONG,
		UNSIGNED_INT, -1, -1}},
	{"move_pages", 279, LONG, 6, {INT, UNSIGNED_LONG, VOID_PP, INT_P,
		INT_P, INT}},
	{"utimensat", 280, INT, 4, {INT, CHAR_P, STRUCT_TIMESPEC_P, INT, -1,
		-1}},
	{"epoll_pwait", 281, INT, 5, {INT, STRUCT_EPOLL_EVENT_P, INT, INT,
		SIGSET_T_P, -1}},
	{"signalfd", 282, INT, 3, {INT, SIGSET_T_P, INT, -1, -1, -1}},
	{"timerfd_create", 283, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"eventfd", 284, INT, 2, {UNSIGNED_INT, INT, -1, -1, -1, -1}},
	{"fallocate", 285, INT, 4, {INT, INT, OFF_T, OFF_T, -1, -1}},
	{"timerfd_settime", 286, INT, 4, {INT, INT, STRUCT_ITIMERSPEC_P,
		STRUCT_ITIMERSPEC_P, -1, -1}},
	{"timerfd_gettime", 287, INT, 2, {INT, STRUCT_ITIMERSPEC_P, -1, -1,
		-1, -1}},
	{"accept4", 288, INT, 4, {INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, INT,
		-1, -1}},
	{"signalfd4", 289, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"eventfd2", 290, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"epoll_create1", 291, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"dup3", 292, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"pipe2", 293, INT, 2, {INT_P, INT, -1, -1, -1, -1}},
	{"inotify_init1", 294, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"preadv", 295, SSIZE_T, 4, {INT, STRUCT_IOVEC_P, INT, OFF_T, -1, -1}},
	{"pwritev", 296, SSIZE_T, 4, {INT, STRUCT_IOVEC_P, INT, OFF_T, -1, -1}},
	{"rt_tgsigqueueinfo", 297, INT, 4, {PID_T, PID_T, INT, SIGINFO_T_P,
		-1, -1}},
	{"perf_event_open", 298, INT, 5, {STRUCT_PERF_EVENT_ATTR_P, PID_T,
		INT, INT, UNSIGNED_LONG, -1}},
	{"recvmmsg", 299, INT, 5, {INT, STRUCT_MMSGHDR_P, UNSIGNED_INT,
		UNSIGNED_INT, STRUCT_TIMESPEC_P, -1}},
	{"fanotify_init", 300, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"fanotify_mark", 301, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"prlimit64", 302, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"name_to_handle_at", 303, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"open_by_handle_at", 304, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"clock_adjtime", 305, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"syncfs", 306, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"sendmmsg", 307, INT, 4, {INT, STRUCT_MMSGHDR_P, UNSIGNED_INT,
		UNSIGNED_INT, -1, -1}},
	{"setns", 308, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"getcpu", 309, INT, 3, {UNSIGNED_INT_P, UNSIGNED_INT_P,
		STRUCT_GETCPU_CACHE_P, -1, -1, -1}},
	{"process_vm_readv", 310, SSIZE_T, 6, {PID_T, STRUCT_IOVEC_P,
		UNSIGNED_LONG, STRUCT_IOVEC_P, UNSIGNED_LONG, UNSIGNED_LONG}},
	{"process_vm_writev", 311, SSIZE_T, 6, {PID_T, STRUCT_IOVEC_P,
		UNSIGNED_LONG, STRUCT_IOVEC_P, UNSIGNED_LONG, UNSIGNED_LONG}},
	{"kcmp", 312, INT, 5, {PID_T, PID_T, INT, UNSIGNED_LONG,
		UNSIGNED_LONG, -1}},
	{"finit_module", 313, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"sched_setattr", 314, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"sched_getattr", 315, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"renameat2", 316, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"seccomp", 317, -1, 0, {-1, -1, -1, -1, -1, -1}}
};

static syscall_t const syscalls_32_g[] = {
	{"restart_syscall", 0, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"exit", 1, VOID, 1, {INT, -1, -1, -1, -1, -1}},
	{"fork", 2, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"read", 3, SSIZE_T, 3, {INT, VOID_P, SIZE_T, -1, -1, -1}},
	{"write", 4, SSIZE_T, 3, {INT, VOID_P, SIZE_T, -1, -1, -1}},
	{"open", 5, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"close", 6, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"waitpid", 7, PID_T, 3, {PID_T, INT_P, INT, -1, -1, -1}},
	{"creat", 8, INT, 2, {CHAR_P, MODE_T, -1, -1, -1, -1}},
	{"link", 9, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"unlink", 10, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"execve", 11, INT, 3, {CHAR_P, CHAR_PP, CHAR_PP, -1, -1, -1}},
	{"chdir", 12, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"time", 13, TIME_T, 1, {TIME_T_P, -1, -1, -1, -1, -1}},
	{"mknod", 14, INT, 3, {CHAR_P, MODE_T, DEV_T, -1, -1, -1}},
	{"chmod", 15, INT, 2, {CHAR_P, MODE_T, -1, -1, -1, -1}},
	{"lchown", 16, INT, 3, {CHAR_P, UID_T, GID_T, -1, -1, -1}},
	{"break", 17, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"oldstat", 18, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"lseek", 19, OFF_T, 3, {INT, OFF_T, INT, -1, -1, -1}},
	{"getpid", 20, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"mount", 21, INT, 5, {CHAR_P, CHAR_P, CHAR_P, UNSIGNED_LONG, VOID_P,
		-1}},
	{"umount", 22, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"setuid", 23, INT, 1, {UID_T, -1, -1, -1, -1, -1}},
	{"getuid", 24, UID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"stime", 25, INT, 1, {TIME_T_P, -1, -1, -1, -1, -1}},
	{"ptrace", 26, LONG, 4, {ENUM___PTRACE_REQUEST, PID_T, VOID_P, VOID_P,
		-1, -1}},
	{"alarm", 27, UNSIGNED_INT, 1, {UNSIGNED_INT, -1, -1, -1, -1, -1}},
	{"oldfstat", 28, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"pause", 29, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"utime", 30, INT, 2, {CHAR_P, STRUCT_UTIMBUF_P, -1, -1, -1, -1}},
	{"stty", 31, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"gtty", 32, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"access", 33, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"nice", 34, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"ftime", 35, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"sync", 36, VOID, 1, {VOID, -1, -1, -1, -1, -1}},
	{"kill", 37, INT, 2, {PID_T, INT, -1, -1, -1, -1}},
	{"rename", 38, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"mkdir", 39, INT, 2, {CHAR_P, MODE_T, -1, -1, -1, -1}},
	{"rmdir", 40, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"dup", 41, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"pipe", 42, INT, 1, {INT_P, -1, -1, -1, -1, -1}},
	{"times", 43, CLOCK_T, 1, {STRUCT_TMS_P, -1, -1, -1, -1, -1}},
	{"prof", 44, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"brk", 45, INT, 1, {VOID_P, -1, -1, -1, -1, -1}},
	{"setgid", 46, INT, 1, {GID_T, -1, -1, -1, -1, -1}},
	{"getgid", 47, GID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"signal", 48, SIGHANDLER_T, 2, {INT, SIGHANDLER_T, -1, -1, -1, -1}},
	{"geteuid", 49, UID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"getegid", 50, GID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"acct", 51, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"umount2", 52, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"lock", 53, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"ioctl", 54, INT, 3, {INT, INT, VARARGS, -1, -1, -1}},
	{"fcntl", 55, INT, 3, {INT, INT, VARARGS, -1, -1, -1}},
	{"mpx", 56, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setpgid", 57, INT, 2, {PID_T, PID_T, -1, -1, -1, -1}},
	{"ulimit", 58, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"oldolduname", 59, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"umask", 60, MODE_T, 1, {MODE_T, -1, -1, -1, -1, -1}},
	{"chroot", 61, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"ustat", 62, INT, 2, {DEV_T, STRUCT_USTAT_P, -1, -1, -1, -1}},
	{"dup2", 63, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"getppid", 64, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"getpgrp", 65, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"setsid", 66, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"sigaction", 67, INT, 3, {INT, STRUCT_SIGACTION_P,
		STRUCT_SIGACTION_P, -1, -1, -1}},
	{"sgetmask", 68, LONG, 1, {VOID, -1, -1, -1, -1, -1}},
	{"ssetmask", 69, LONG, 1, {LONG, -1, -1, -1, -1, -1}},
	{"setreuid", 70, INT, 2, {UID_T, UID_T, -1, -1, -1, -1}},
	{"setregid", 71, INT, 2, {GID_T, GID_T, -1, -1, -1, -1}},
	{"sigsuspend", 72, INT, 1, {SIGSET_T_P, -1, -1, -1, -1, -1}},
	{"sigpending", 73, INT, 1, {SIGSET_T_P, -1, -1, -1, -1, -1}},
	{"sethostname", 74, INT, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"setrlimit", 75, INT, 2, {INT, STRUCT_RLIMIT_P, -1, -1, -1, -1}},
	{"getrlimit", 76, INT, 2, {INT, STRUCT_RLIMIT_P, -1, -1, -1, -1}},
	{"getrusage", 77, INT, 2, {INT, STRUCT_RUSAGE_P, -1, -1, -1, -1}},
	{"gettimeofday", 78, INT, 2, {STRUCT_TIMEVAL_P, STRUCT_TIMEZONE_P, -1,
		-1, -1, -1}},
	{"settimeofday", 79, INT, 2, {STRUCT_TIMEVAL_P, STRUCT_TIMEZONE_P, -1,
		-1, -1, -1}},
	{"getgroups", 80, INT, 2, {INT, GID_T_P, -1, -1, -1, -1}},
	{"setgroups", 81, INT, 2, {SIZE_T, GID_T_P, -1, -1, -1, -1}},
	{"select", 82, INT, 5, {INT, FD_SET_P, FD_SET_P, FD_SET_P,
		STRUCT_TIMEVAL_P, -1}},
	{"symlink", 83, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"oldlstat", 84, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"readlink", 85, SSIZE_T, 3, {CHAR_P, CHAR_P, SIZE_T, -1, -1, -1}},
	{"uselib", 86, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"swapon", 87, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"reboot", 88, INT, 4, {INT, INT, INT, VOID_P, -1, -1}},
	{"readdir", 89, INT, 3, {UNSIGNED_INT, STRUCT_OLD_LINUX_DIRENT_P,
		UNSIGNED_INT, -1, -1, -1}},
	{"mmap", 90, VOID_P, 6, {VOID_P, SIZE_T, INT, INT, INT, OFF_T}},
	{"munmap", 91, INT, 2, {VOID_P, SIZE_T, -1, -1, -1, -1}},
	{"truncate", 92, INT, 2, {CHAR_P, OFF_T, -1, -1, -1, -1}},
	{"ftruncate", 93, INT, 2, {INT, OFF_T, -1, -1, -1, -1}},
	{"fchmod", 94, INT, 2, {INT, MODE_T, -1, -1, -1, -1}},
	{"fchown", 95, INT, 3, {INT, UID_T, GID_T, -1, -1, -1}},
	{"getpriority", 96, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"setpriority", 97, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"profil", 98, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"statfs", 99, INT, 2, {CHAR_P, STRUCT_STATFS_P, -1, -1, -1, -1}},
	{"fstatfs", 100, INT, 2, {INT, STRUCT_STATFS_P, -1, -1, -1, -1}},
	{"ioperm", 101, INT, 3, {UNSIGNED_LONG, UNSIGNED_LONG, INT, -1, -1,
		-1}},
	{"socketcall", 102, INT, 2, {INT, UNSIGNED_LONG_P, -1, -1, -1, -1}},
	{"syslog", 103, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"setitimer", 104, INT, 3, {INT, STRUCT_ITIMERVAL_P,
		STRUCT_ITIMERVAL_P, -1, -1, -1}},
	{"getitimer", 105, INT, 2, {INT, STRUCT_ITIMERVAL_P, -1, -1, -1, -1}},
	{"stat", 106, INT, 2, {CHAR_P, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"lstat", 107, INT, 2, {CHAR_P, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"fstat", 108, INT, 2, {INT, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"olduname", 109, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"iopl", 110, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"vhangup", 111, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"idle", 112, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"vm86old", 113, INT, 1, {STRUCT_VM86_STRUCT_P, -1, -1, -1, -1, -1}},
	{"wait4", 114, PID_T, 4, {PID_T, INT_P, INT, STRUCT_RUSAGE_P, -1, -1}},
	{"swapoff", 115, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"sysinfo", 116, INT, 1, {STRUCT_SYSINFO_P, -1, -1, -1, -1, -1}},
	{"ipc", 117, INT, 6, {UNSIGNED_INT, INT, INT, INT, VOID_P, LONG}},
	{"fsync", 118, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"sigreturn", 119, INT, 1, {UNSIGNED_LONG, -1, -1, -1, -1, -1}},
	{"clone", 120, INT, 5, {INT, VOID_P, INT, VOID_P, VARARGS, -1}},
	{"setdomainname", 121, INT, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"uname", 122, INT, 1, {STRUCT_UTSNAME_P, -1, -1, -1, -1, -1}},
	{"modify_ldt", 123, INT, 3, {INT, VOID_P, UNSIGNED_LONG, -1, -1, -1}},
	{"adjtimex", 124, INT, 1, {STRUCT_TIMEX_P, -1, -1, -1, -1, -1}},
	{"mprotect", 125, INT, 3, {VOID_P, SIZE_T, INT, -1, -1, -1}},
	{"sigprocmask", 126, INT, 3, {INT, SIGSET_T_P, SIGSET_T_P, -1, -1, -1}},
	{"create_module", 127, CADDR_T, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"init_module", 128, INT, 3, {VOID_P, UNSIGNED_LONG, CHAR_P, -1, -1,
		-1}},
	{"delete_module", 129, INT, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"get_kernel_syms", 130, INT, 1, {STRUCT_KERNEL_SYM_P, -1, -1, -1, -1,
		-1}},
	{"quotactl", 131, INT, 4, {INT, CHAR_P, INT, CADDR_T, -1, -1}},
	{"getpgid", 132, PID_T, 1, {PID_T, -1, -1, -1, -1, -1}},
	{"fchdir", 133, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"bdflush", 134, INT, 2, {INT, LONG_P, -1, -1, -1, -1}},
	{"sysfs", 135, INT, 2, {INT, CHAR_P, -1, -1, -1, -1}},
	{"personality", 136, INT, 1, {UNSIGNED_LONG, -1, -1, -1, -1, -1}},
	{"afs_syscall", 137, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setfsuid", 138, INT, 1, {UID_T, -1, -1, -1, -1, -1}},
	{"setfsgid", 139, INT, 1, {UID_T, -1, -1, -1, -1, -1}},
	{"_llseek", 140, INT, 5, {UNSIGNED_INT, UNSIGNED_LONG, UNSIGNED_LONG,
		LOFF_T_P, UNSIGNED_INT, -1}},
	{"getdents", 141, INT, 3, {UNSIGNED_INT, STRUCT_LINUX_DIRENT_P,
		UNSIGNED_INT, -1, -1, -1}},
	{"_newselect", 142, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"flock", 143, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"msync", 144, INT, 3, {VOID_P, SIZE_T, INT, -1, -1, -1}},
	{"readv", 145, SSIZE_T, 3, {INT, STRUCT_IOVEC_P, INT, -1, -1, -1}},
	{"writev", 146, SSIZE_T, 3, {INT, STRUCT_IOVEC_P, INT, -1, -1, -1}},
	{"getsid", 147, PID_T, 1, {PID_T, -1, -1, -1, -1, -1}},
	{"fdatasync", 148, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"_sysctl", 149, INT, 1, {STRUCT___SYSCTL_ARGS_P, -1, -1, -1, -1, -1}},
	{"mlock", 150, INT, 2, {VOID_P, SIZE_T, -1, -1, -1, -1}},
	{"munlock", 151, INT, 2, {VOID_P, SIZE_T, -1, -1, -1, -1}},
	{"mlockall", 152, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"munlockall", 153, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"sched_setparam", 154, INT, 2, {PID_T, STRUCT_SCHED_PARAM_P, -1, -1,
		-1, -1}},
	{"sched_getparam", 155, INT, 2, {PID_T, STRUCT_SCHED_PARAM_P, -1, -1,
		-1, -1}},
	{"sched_setscheduler", 156, INT, 3, {PID_T, INT, STRUCT_SCHED_PARAM_P,
		-1, -1, -1}},
	{"sched_getscheduler", 157, INT, 1, {PID_T, -1, -1, -1, -1, -1}},
	{"sched_yield", 158, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"sched_get_priority_max", 159, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"sched_get_priority_min", 160, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"sched_rr_get_interval", 161, INT, 2, {PID_T, STRUCT_TIMESPEC_P, -1,
		-1, -1, -1}},
	{"nanosleep", 162, INT, 2, {STRUCT_TIMESPEC_P, STRUCT_TIMESPEC_P, -1,
		-1, -1, -1}},
	{"mremap", 163, VOID_P, 5, {VOID_P, SIZE_T, SIZE_T, INT, VARARGS, -1}},
	{"setresuid", 164, INT, 3, {UID_T, UID_T, UID_T, -1, -1, -1}},
	{"getresuid", 165, INT, 3, {UID_T_P, UID_T_P, UID_T_P, -1, -1, -1}},
	{"vm86", 166, INT, 1, {STRUCT_VM86_STRUCT_P, -1, -1, -1, -1, -1}},
	{"query_module", 167, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"poll", 168, INT, 3, {STRUCT_POLLFD_P, NFDS_T, INT, -1, -1, -1}},
	{"nfsservctl", 169, LONG, 3, {INT, STRUCT_NFSCTL_ARG_P,
		UNION_NFSCTL_RES_P, -1, -1, -1}},
	{"setresgid", 170, INT, 3, {GID_T, GID_T, GID_T, -1, -1, -1}},
	{"getresgid", 171, INT, 3, {GID_T_P, GID_T_P, GID_T_P, -1, -1, -1}},
	{"prctl", 172, INT, 5, {INT, UNSIGNED_LONG, UNSIGNED_LONG,
		UNSIGNED_LONG, UNSIGNED_LONG, -1}},
	{"rt_sigreturn", 173, INT, 1, {UNSIGNED_LONG, -1, -1, -1, -1, -1}},
	{"rt_sigaction", 174, INT, 3, {INT, STRUCT_SIGACTION_P,
		STRUCT_SIGACTION_P, -1, -1, -1}},
	{"rt_sigprocmask", 175, INT, 3, {INT, SIGSET_T_P, SIGSET_T_P, -1, -1,
		-1}},
	{"rt_sigpending", 176, INT, 1, {SIGSET_T_P, -1, -1, -1, -1, -1}},
	{"rt_sigtimedwait", 177, INT, 3, {SIGSET_T_P, SIGINFO_T_P,
		STRUCT_TIMESPEC_P, -1, -1, -1}},
	{"rt_sigqueueinfo", 178, INT, 3, {PID_T, INT, SIGINFO_T_P, -1, -1, -1}},
	{"rt_sigsuspend", 179, INT, 1, {SIGSET_T_P, -1, -1, -1, -1, -1}},
	{"pread64", 180, SSIZE_T, 4, {INT, VOID_P, SIZE_T, OFF_T, -1, -1}},
	{"pwrite64", 181, SSIZE_T, 4, {INT, VOID_P, SIZE_T, OFF_T, -1, -1}},
	{"chown", 182, INT, 3, {CHAR_P, UID_T, GID_T, -1, -1, -1}},
	{"getcwd", 183, CHAR_P, 2, {CHAR_P, SIZE_T, -1, -1, -1, -1}},
	{"capget", 184, INT, 2, {CAP_USER_HEADER_T, CAP_USER_DATA_T, -1, -1,
		-1, -1}},
	{"capset", 185, INT, 2, {CAP_USER_HEADER_T, CAP_USER_DATA_T, -1, -1,
		-1, -1}},
	{"sigaltstack", 186, INT, 2, {STACK_T_P, STACK_T_P, -1, -1, -1, -1}},
	{"sendfile", 187, SSIZE_T, 4, {INT, INT, OFF_T_P, SIZE_T, -1, -1}},
	{"getpmsg", 188, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"putpmsg", 189, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"vfork", 190, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"ugetrlimit", 191, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"mmap2", 192, VOID_P, 6, {VOID_P, SIZE_T, INT, INT, INT, OFF_T}},
	{"truncate64", 193, INT, 2, {CHAR_P, OFF_T, -1, -1, -1, -1}},
	{"ftruncate64", 194, INT, 2, {INT, OFF_T, -1, -1, -1, -1}},
	{"stat64", 195, INT, 2, {CHAR_P, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"lstat64", 196, INT, 2, {CHAR_P, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"fstat64", 197, INT, 2, {INT, STRUCT_STAT_P, -1, -1, -1, -1}},
	{"lchown32", 198, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"getuid32", 199, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"getgid32", 200, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"geteuid32", 201, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"getegid32", 202, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setreuid32", 203, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setregid32", 204, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"getgroups32", 205, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setgroups32", 206, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"fchown32", 207, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setresuid32", 208, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"getresuid32", 209, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setresgid32", 210, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"getresgid32", 211, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"chown32", 212, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setuid32", 213, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setgid32", 214, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setfsuid32", 215, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"setfsgid32", 216, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"pivot_root", 217, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"mincore", 218, INT, 3, {VOID_P, SIZE_T, UNSIGNED_CHAR_P, -1, -1, -1}},
	{"madvise", 219, INT, 3, {VOID_P, SIZE_T, INT, -1, -1, -1}},
	{"getdents64", 220, INT, 3, {UNSIGNED_INT, STRUCT_LINUX_DIRENT_P,
		UNSIGNED_INT, -1, -1, -1}},
	{"fcntl64", 221, INT, 3, {INT, INT, VARARGS, -1, -1, -1}},
	{"gettid", 224, PID_T, 1, {VOID, -1, -1, -1, -1, -1}},
	{"readahead", 225, SSIZE_T, 3, {INT, OFF64_T, SIZE_T, -1, -1, -1}},
	{"setxattr", 226, INT, 5, {CHAR_P, CHAR_P, VOID_P, SIZE_T, INT, -1}},
	{"lsetxattr", 227, INT, 5, {CHAR_P, CHAR_P, VOID_P, SIZE_T, INT, -1}},
	{"fsetxattr", 228, INT, 5, {INT, CHAR_P, VOID_P, SIZE_T, INT, -1}},
	{"getxattr", 229, SSIZE_T, 4, {CHAR_P, CHAR_P, VOID_P, SIZE_T, -1, -1}},
	{"lgetxattr", 230, SSIZE_T, 4, {CHAR_P, CHAR_P, VOID_P, SIZE_T, -1,
		-1}},
	{"fgetxattr", 231, SSIZE_T, 4, {INT, CHAR_P, VOID_P, SIZE_T, -1, -1}},
	{"listxattr", 232, SSIZE_T, 3, {CHAR_P, CHAR_P, SIZE_T, -1, -1, -1}},
	{"llistxattr", 233, SSIZE_T, 3, {CHAR_P, CHAR_P, SIZE_T, -1, -1, -1}},
	{"flistxattr", 234, SSIZE_T, 3, {INT, CHAR_P, SIZE_T, -1, -1, -1}},
	{"removexattr", 235, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"lremovexattr", 236, INT, 2, {CHAR_P, CHAR_P, -1, -1, -1, -1}},
	{"fremovexattr", 237, INT, 2, {INT, CHAR_P, -1, -1, -1, -1}},
	{"tkill", 238, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"sendfile64", 239, SSIZE_T, 4, {INT, INT, OFF_T_P, SIZE_T, -1, -1}},
	{"futex", 240, INT, 6, {INT_P, INT, INT, STRUCT_TIMESPEC_P, INT_P,
		INT}},
	{"sched_setaffinity", 241, INT, 3, {PID_T, SIZE_T, CPU_SET_T_P, -1, -1,
		-1}},
	{"sched_getaffinity", 242, INT, 3, {PID_T, SIZE_T, CPU_SET_T_P, -1, -1,
		-1}},
	{"set_thread_area", 243, INT, 1, {STRUCT_USER_DESC_P, -1, -1, -1, -1,
		-1}},
	{"get_thread_area", 244, INT, 1, {STRUCT_USER_DESC_P, -1, -1, -1, -1,
		-1}},
	{"io_setup", 245, INT, 2, {UNSIGNED_INT, AIO_CONTEXT_T_P, -1, -1, -1,
		-1}},
	{"io_destroy", 246, INT, 1, {AIO_CONTEXT_T, -1, -1, -1, -1, -1}},
	{"io_getevents", 247, INT, 5, {AIO_CONTEXT_T, LONG, LONG,
		STRUCT_IO_EVENT_P, STRUCT_TIMESPEC_P, -1}},
	{"io_submit", 248, INT, 3, {AIO_CONTEXT_T, LONG, STRUCT_IOCB_PP, -1,
		-1, -1}},
	{"io_cancel", 249, INT, 3, {AIO_CONTEXT_T, STRUCT_IOCB_P,
		STRUCT_IO_EVENT_P, -1, -1, -1}},
	{"fadvise64", 250, INT, 4, {INT, OFF_T, OFF_T, INT, -1, -1}},
	{"exit_group", 252, VOID, 1, {INT, -1, -1, -1, -1, -1}},
	{"lookup_dcookie", 253, INT, 3, {U64, CHAR_P, SIZE_T, -1, -1, -1}},
	{"epoll_create", 254, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"epoll_ctl", 255, INT, 4, {INT, INT, INT, STRUCT_EPOLL_EVENT_P, -1,
		-1}},
	{"epoll_wait", 256, INT, 4, {INT, STRUCT_EPOLL_EVENT_P, INT, INT, -1,
		-1}},
	{"remap_file_pages", 257, INT, 5, {VOID_P, SIZE_T, INT, SSIZE_T, INT,
		-1}},
	{"set_tid_address", 258, LONG, 1, {INT_P, -1, -1, -1, -1, -1}},
	{"timer_create", 259, INT, 3, {CLOCKID_T, STRUCT_SIGEVENT_P, TIMER_T_P,
		-1, -1, -1}},
	{"timer_settime", 260, INT, 4, {TIMER_T, INT, STRUCT_ITIMERSPEC_P,
		STRUCT_ITIMERSPEC_P, -1, -1}},
	{"timer_gettime", 261, INT, 2, {TIMER_T, STRUCT_ITIMERSPEC_P, -1, -1,
		-1, -1}},
	{"timer_getoverrun", 262, INT, 1, {TIMER_T, -1, -1, -1, -1, -1}},
	{"timer_delete", 263, INT, 1, {TIMER_T, -1, -1, -1, -1, -1}},
	{"clock_settime", 264, INT, 2, {CLOCKID_T, STRUCT_TIMESPEC_P, -1, -1,
		-1, -1}},
	{"clock_gettime", 265, INT, 2, {CLOCKID_T, STRUCT_TIMESPEC_P, -1, -1,
		-1, -1}},
	{"clock_getres", 266, INT, 2, {CLOCKID_T, STRUCT_TIMESPEC_P, -1, -1,
		-1, -1}},
	{"clock_nanosleep", 267, INT, 4, {CLOCKID_T, INT, STRUCT_TIMESPEC_P,
		STRUCT_TIMESPEC_P, -1, -1}},
	{"statfs64", 268, INT, 2, {CHAR_P, STRUCT_STATFS_P, -1, -1, -1, -1}},
	{"fstatfs64", 269, INT, 2, {INT, STRUCT_STATFS_P, -1, -1, -1, -1}},
	{"tgkill", 270, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"utimes", 271, INT, 2, {CHAR_P, STRUCT_TIMEVAL_P, -1, -1, -1, -1}},
	{"fadvise64_64", 272, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"vserver", 273, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"mbind", 274, INT, 6, {VOID_P, UNSIGNED_LONG, INT, UNSIGNED_LONG_P,
		UNSIGNED_LONG, UNSIGNED_INT}},
	{"get_mempolicy", 275, INT, 5, {INT_P, UNSIGNED_LONG_P, UNSIGNED_LONG,
		UNSIGNED_LONG, UNSIGNED_LONG, -1}},
	{"set_mempolicy", 276, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"mq_open", 277, MQD_T, 2, {CHAR_P, INT, -1, -1, -1, -1}},
	{"mq_unlink", 278, INT, 1, {CHAR_P, -1, -1, -1, -1, -1}},
	{"mq_timedsend", 279, INT, 5, {MQD_T, CHAR_P, SIZE_T, UNSIGNED_INT,
		STRUCT_TIMESPEC_P, -1}},
	{"mq_timedreceive", 280, SSIZE_T, 5, {MQD_T, CHAR_P, SIZE_T,
		UNSIGNED_INT_P, STRUCT_TIMESPEC_P, -1}},
	{"mq_notify", 281, INT, 2, {MQD_T, STRUCT_SIGEVENT_P, -1, -1, -1, -1}},
	{"mq_getsetattr", 282, INT, 3, {MQD_T, STRUCT_MQ_ATTR_P,
		STRUCT_MQ_ATTR_P, -1, -1, -1}},
	{"kexec_load", 283, LONG, 4, {UNSIGNED_LONG, UNSIGNED_LONG,
		STRUCT_KEXEC_SEGMENT_P, UNSIGNED_LONG, -1, -1}},
	{"waitid", 284, INT, 4, {IDTYPE_T, ID_T, SIGINFO_T_P, INT, -1, -1}},
	{"add_key", 286, KEY_SERIAL_T, 5, {CHAR_P, CHAR_P, VOID_P, SIZE_T,
		KEY_SERIAL_T, -1}},
	{"request_key", 287, KEY_SERIAL_T, 4, {CHAR_P, CHAR_P, CHAR_P,
		KEY_SERIAL_T, -1, -1}},
	{"keyctl", 288, LONG, 2, {INT, VARARGS, -1, -1, -1, -1}},
	{"ioprio_set", 289, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"ioprio_get", 290, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"inotify_init", 291, INT, 1, {VOID, -1, -1, -1, -1, -1}},
	{"inotify_add_watch", 292, INT, 3, {INT, CHAR_P, UINT32_T, -1, -1, -1}},
	{"inotify_rm_watch", 293, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"migrate_pages", 294, LONG, 4, {INT, UNSIGNED_LONG, UNSIGNED_LONG_P,
		UNSIGNED_LONG_P, -1, -1}},
	{"openat", 295, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"mkdirat", 296, INT, 3, {INT, CHAR_P, MODE_T, -1, -1, -1}},
	{"mknodat", 297, INT, 4, {INT, CHAR_P, MODE_T, DEV_T, -1, -1}},
	{"fchownat", 298, INT, 5, {INT, CHAR_P, UID_T, GID_T, INT, -1}},
	{"futimesat", 299, INT, 3, {INT, CHAR_P, STRUCT_TIMEVAL_P, -1, -1, -1}},
	{"fstatat64", 300, INT, 4, {INT, CHAR_P, STRUCT_STAT_P, INT, -1, -1}},
	{"unlinkat", 301, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"renameat", 302, INT, 4, {INT, CHAR_P, INT, CHAR_P, -1, -1}},
	{"linkat", 303, INT, 5, {INT, CHAR_P, INT, CHAR_P, INT, -1}},
	{"symlinkat", 304, INT, 3, {CHAR_P, INT, CHAR_P, -1, -1, -1}},
	{"readlinkat", 305, INT, 4, {INT, CHAR_P, CHAR_P, SIZE_T, -1, -1}},
	{"fchmodat", 306, INT, 4, {INT, CHAR_P, MODE_T, INT, -1, -1}},
	{"faccessat", 307, INT, 4, {INT, CHAR_P, INT, INT, -1, -1}},
	{"pselect6", 308, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"ppoll", 309, INT, 4, {STRUCT_POLLFD_P, NFDS_T, STRUCT_TIMESPEC_P,
		SIGSET_T_P, -1, -1}},
	{"unshare", 310, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"set_robust_list", 311, LONG, 2, {STRUCT_ROBUST_LIST_HEAD_P, SIZE_T,
		-1, -1, -1, -1}},
	{"get_robust_list", 312, LONG, 3, {INT, STRUCT_ROBUST_LIST_HEAD_PP,
		SIZE_T_P, -1, -1, -1}},
	{"splice", 313, SSIZE_T, 6, {INT, LOFF_T_P, INT, LOFF_T_P, SIZE_T,
		UNSIGNED_INT}},
	{"sync_file_range", 314, INT, 4, {INT, OFF64_T, OFF64_T, UNSIGNED_INT,
		-1, -1}},
	{"tee", 315, SSIZE_T, 4, {INT, INT, SIZE_T, UNSIGNED_INT, -1, -1}},
	{"vmsplice", 316, SSIZE_T, 4, {INT, STRUCT_IOVEC_P, UNSIGNED_LONG,
		UNSIGNED_INT, -1, -1}},
	{"move_pages", 317, LONG, 6, {INT, UNSIGNED_LONG, VOID_PP, INT_P,
		INT_P, INT}},
	{"getcpu", 318, INT, 3, {UNSIGNED_INT_P, UNSIGNED_INT_P,
		STRUCT_GETCPU_CACHE_P, -1, -1, -1}},
	{"epoll_pwait", 319, INT, 5, {INT, STRUCT_EPOLL_EVENT_P, INT, INT,
		SIGSET_T_P, -1}},
	{"utimensat", 320, INT, 4, {INT, CHAR_P, STRUCT_TIMESPEC_P, INT, -1,
		-1}},
	{"signalfd", 321, INT, 3, {INT, SIGSET_T_P, INT, -1, -1, -1}},
	{"timerfd_create", 322, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"eventfd", 323, INT, 2, {UNSIGNED_INT, INT, -1, -1, -1, -1}},
	{"fallocate", 324, INT, 4, {INT, INT, OFF_T, OFF_T, -1, -1}},
	{"timerfd_settime", 325, INT, 4, {INT, INT, STRUCT_ITIMERSPEC_P,
		STRUCT_ITIMERSPEC_P, -1, -1}},
	{"timerfd_gettime", 326, INT, 2, {INT, STRUCT_ITIMERSPEC_P, -1, -1, -1,
		-1}},
	{"signalfd4", 327, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"eventfd2", 328, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"epoll_create1", 329, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"dup3", 330, INT, 3, {INT, INT, INT, -1, -1, -1}},
	{"pipe2", 331, INT, 2, {INT_P, INT, -1, -1, -1, -1}},
	{"inotify_init1", 332, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"preadv", 333, SSIZE_T, 4, {INT, STRUCT_IOVEC_P, INT, OFF_T, -1, -1}},
	{"pwritev", 334, SSIZE_T, 4, {INT, STRUCT_IOVEC_P, INT, OFF_T, -1, -1}},
	{"rt_tgsigqueueinfo", 335, INT, 4, {PID_T, PID_T, INT, SIGINFO_T_P, -1,
		-1}},
	{"perf_event_open", 336, INT, 5, {STRUCT_PERF_EVENT_ATTR_P, PID_T, INT,
		INT, UNSIGNED_LONG, -1}},
	{"recvmmsg", 337, INT, 5, {INT, STRUCT_MMSGHDR_P, UNSIGNED_INT,
		UNSIGNED_INT, STRUCT_TIMESPEC_P, -1}},
	{"fanotify_init", 338, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"fanotify_mark", 339, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"prlimit64", 340, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"name_to_handle_at", 341, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"open_by_handle_at", 342, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"clock_adjtime", 343, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"syncfs", 344, INT, 1, {INT, -1, -1, -1, -1, -1}},
	{"sendmmsg", 345, INT, 4, {INT, STRUCT_MMSGHDR_P, UNSIGNED_INT,
		UNSIGNED_INT, -1, -1}},
	{"setns", 346, INT, 2, {INT, INT, -1, -1, -1, -1}},
	{"process_vm_readv", 347, SSIZE_T, 6, {PID_T, STRUCT_IOVEC_P,
		UNSIGNED_LONG, STRUCT_IOVEC_P, UNSIGNED_LONG, UNSIGNED_LONG}},
	{"process_vm_writev", 348, SSIZE_T, 6, {PID_T, STRUCT_IOVEC_P,
		UNSIGNED_LONG, STRUCT_IOVEC_P, UNSIGNED_LONG, UNSIGNED_LONG}},
	{"kcmp", 349, INT, 5, {PID_T, PID_T, INT, UNSIGNED_LONG, UNSIGNED_LONG,
		-1}},
	{"finit_module", 350, INT, 3, {INT, CHAR_P, INT, -1, -1, -1}},
	{"sched_setattr", 351, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"sched_getattr", 352, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"renameat2", 353, -1, 0, {-1, -1, -1, -1, -1, -1}},
	{"seccomp", 354, -1, 0, {-1, -1, -1, -1, -1, -1}}
};

// Define the syscall numbers for x86_64 (example numbers, adjust as necessary)
enum syscall_number {
    SYS_read = 0,
    SYS_write = 1,
    SYS_open = 2,
    SYS_close = 3,
    SYS_stat = 4,
    SYS_fstat = 5,
    SYS_lstat = 6,
    SYS_poll = 7,
    SYS_lseek = 8,
    SYS_mmap = 9,
    SYS_mprotect = 10,
    SYS_munmap = 11,
    SYS_brk = 12,
    SYS_rt_sigaction = 13,
    SYS_rt_sigprocmask = 14,
    SYS_rt_sigreturn = 15,
    SYS_ioctl = 16,
    SYS_pread64 = 17,
    SYS_pwrite64 = 18,
    SYS_readv = 19,
    SYS_writev = 20,
    SYS_access = 21,
    SYS_pipe = 22,
    SYS_select = 23,
    SYS_sched_yield = 24,
    SYS_mremap = 25,
    SYS_msync = 26,
    SYS_mincore = 27,
    SYS_madvise = 28,
    SYS_shmget = 29,
    SYS_shmat = 30,
    SYS_shmctl = 31,
    SYS_dup = 32,
    SYS_dup2 = 33,
    SYS_pause = 34,
    SYS_nanosleep = 35,
    SYS_getitimer = 36,
    SYS_alarm = 37,
    SYS_setitimer = 38,
    SYS_getpid = 39,
    SYS_sendfile = 40,
    SYS_socket = 41,
    SYS_connect = 42,
    SYS_accept = 43,
    SYS_sendto = 44,
    SYS_recvfrom = 45,
    SYS_shutdown = 46,
    SYS_bind = 47,
    SYS_listen = 48,
    SYS_getsockname = 49,
    SYS_getpeername = 50,
    SYS_socketpair = 51,
    SYS_setsockopt = 52,
    SYS_getsockopt = 53,
    SYS_clone = 54,
    SYS_fork = 55,
    SYS_vfork = 56,
    SYS_execve = 57,
    SYS_exit = 60,
    SYS_wait4 = 61,
    SYS_kill = 62,
    SYS_uname = 63,
    SYS_semget = 64,
    SYS_semop = 65,
    SYS_semctl = 66,
    SYS_shmdt = 67,
    SYS_msgget = 68,
    SYS_msgsnd = 69,
    SYS_msgrcv = 70,
    SYS_msgctl = 71,
    SYS_fcntl = 72,
    SYS_flock = 73,
    SYS_fsync = 74,
    SYS_fdatasync = 75,
    SYS_truncate = 76,
    SYS_ftruncate = 77,
    SYS_getdents = 78,
    SYS_getcwd = 79,
    SYS_chdir = 80,
    SYS_fchdir = 81,
    SYS_rename = 82,
    SYS_mkdir = 83,
    SYS_rmdir = 84,
    SYS_creat = 85,
    SYS_link = 86,
    SYS_unlink = 87,
    SYS_symlink = 88,
    SYS_readlink = 89,
    SYS_chmod = 90,
    SYS_fchmod = 91,
    SYS_chown = 92,
    SYS_fchown = 93,
    SYS_lchown = 94,
    SYS_umask = 95,
    SYS_gettimeofday = 96,
    SYS_getrlimit = 97,
    SYS_getrusage = 98,
    SYS_sysinfo = 99,
    SYS_times = 100,
    SYS_ptrace = 101,
    SYS_getuid = 102,
    SYS_syslog = 103,
    SYS_getgid = 104,
    SYS_setuid = 105,
    SYS_setgid = 106,
    SYS_geteuid = 107,
    SYS_getegid = 108,
    SYS_setpgid = 109,
    SYS_getppid = 110,
    SYS_getpgrp = 111,
    SYS_setsid = 112,
    SYS_setreuid = 113,
    SYS_setregid = 114,
    SYS_getgroups = 115,
    SYS_setgroups = 116,
    SYS_setresuid = 117,
    SYS_getresuid = 118,
    SYS_setresgid = 119,
    SYS_getresgid = 120,
    SYS_getpgid = 121,
    SYS_setfsuid = 122,
    SYS_setfsgid = 123,
    SYS_getsid = 124,
    SYS_capget = 125,
    SYS_capset = 126,
    SYS_rt_sigpending = 127,
    SYS_rt_sigtimedwait = 128,
    SYS_rt_sigqueueinfo = 129,
    SYS_rt_sigsuspend = 130,
    SYS_sigaltstack = 131,
    SYS_utime = 132,
    SYS_mknod = 133,
    SYS_personality = 135,
    SYS_ustat = 136,
    SYS_statfs = 137,
    SYS_fstatfs = 138,
    SYS_sysfs = 139,
    SYS_getpriority = 140,
    SYS_setpriority = 141,
    SYS_sched_setparam = 142,
    SYS_sched_getparam = 143,
    SYS_sched_setscheduler = 144,
    SYS_sched_getscheduler = 145,
    SYS_sched_get_priority_max = 146,
    SYS_sched_get_priority_min = 147,
    SYS_sched_rr_get_interval = 148,
    SYS_mlock = 149,
    SYS_munlock = 150,
    SYS_mlockall = 151,
    SYS_munlockall = 152,
    SYS_vhangup = 153,
    SYS_modify_ldt = 154,
    SYS_pivot_root = 155,
    SYS_sysctl = 156,
    SYS_prctl = 157,
    SYS_arch_prctl = 158,
    SYS_adjtimex = 159,
    SYS_setrlimit = 160,
    SYS_chroot = 161,
    SYS_sync = 162,
    SYS_acct = 163,
    SYS_settimeofday = 164,
    SYS_mount = 165,
    SYS_umount2 = 166,
    SYS_swapon = 167,
    SYS_swapoff = 168,
    SYS_reboot = 169,
    SYS_sethostname = 170,
    SYS_setdomainname = 171,
    SYS_iopl = 172,
    SYS_ioperm = 173,
    SYS_create_module = 174,
    SYS_init_module = 175,
    SYS_delete_module = 176,
    SYS_get_kernel_syms = 177,
    SYS_query_module = 178,
    SYS_quotactl = 179,
    SYS_nfsservctl = 180,
    SYS_getpmsg = 181,
    SYS_putpmsg = 182,
    SYS_afs_syscall = 183,
    SYS_tuxcall = 184,
    SYS_security = 185,
    SYS_gettid = 186,
    SYS_readahead = 187,
    SYS_setxattr = 188,
    SYS_lsetxattr = 189,
    SYS_fsetxattr = 190,
    SYS_getxattr = 191,
    SYS_lgetxattr = 192,
    SYS_fgetxattr = 193,
    SYS_listxattr = 194,
    SYS_llistxattr = 195,
    SYS_flistxattr = 196,
    SYS_removexattr = 197,
    SYS_lremovexattr = 198,
    SYS_fremovexattr = 199,
    SYS_tkill = 200,
    SYS_time = 201,
    SYS_futex = 202,
    SYS_sched_setaffinity = 203,
    SYS_sched_getaffinity = 204,
    SYS_set_thread_area = 205,
    SYS_get_thread_area = 206,
    SYS_io_setup = 207,
    SYS_io_destroy = 208,
    SYS_io_getevents = 209,
    SYS_io_submit = 210,
    SYS_io_cancel = 211,
    SYS_fadvise64 = 212,
    SYS_exit_group = 213,
    SYS_lookup_dcookie = 214,
    SYS_epoll_create = 215,
    SYS_epoll_ctl = 216,
    SYS_epoll_wait = 217,
    SYS_remap_file_pages = 218,
    SYS_set_tid_address = 219,
    SYS_timer_create = 220,
    SYS_timer_settime = 221,
    SYS_timer_gettime = 222,
    SYS_timer_getoverrun = 223,
    SYS_timer_delete = 224,
    SYS_clock_settime = 225,
    SYS_clock_gettime = 226,
    SYS_clock_getres = 227,
    SYS_clock_nanosleep = 228,
    SYS_syslog = 229,
    SYS_ptrace = 230,
    SYS_sched_setparam = 231,
    SYS_sched_getparam = 232,
    SYS_sched_setattr = 233,
    SYS_sched_getattr = 234,
    SYS_sched_yield = 235,
    SYS_sched_getscheduler = 236,
    SYS_sched_get_priority_max = 237,
    SYS_sched_get_priority_min = 238,
    SYS_sched_rr_get_interval = 239,
    SYS_pread64 = 240,
    SYS_pwrite64 = 241,
    SYS_preadv = 242,
    SYS_pwritev = 243,
    SYS_fallocate = 244,
    SYS_pselect6 = 245,
    SYS_ppoll = 246,
    SYS_unshare = 247,
    SYS_set_robust_list = 248,
    SYS_get_robust_list = 249,
    SYS_splice = 250,
    SYS_tee = 251,
    SYS_sync_file_range = 252,
    SYS_vmsplice = 253,
    SYS_move_pages = 254,
    SYS_utimensat = 255,
    SYS_epoll_pwait = 256,
    SYS_signalfd = 257,
    SYS_timerfd_create = 258,
    SYS_eventfd = 259,
    SYS_fallocate = 260,
    SYS_timerfd_settime = 261,
    SYS_timerfd_gettime = 262,
    SYS_signalfd4 = 263,
    SYS_eventfd2 = 264,
    SYS_epoll_create1 = 265,
    SYS_dup3 = 266,
    SYS_pipe2 = 267,
    SYS_inotify_init1 = 268,
    SYS_preadv2 = 269,
    SYS_pwritev2 = 270,
    SYS_rt_tgsigqueueinfo = 271,
    SYS_perf_event_open = 272,
    SYS_recvmmsg = 273,
    SYS_fanotify_init = 274,
    SYS_fanotify_mark = 275,
    SYS_prlimit64 = 276,
    SYS_name_to_handle_at = 277,
    SYS_open_by_handle_at = 278,
    SYS_clock_adjtime = 279,
    SYS_syncfs = 280,
    SYS_sendmmsg = 281,
    SYS_setns = 282,
    SYS_getcpu = 283,
    SYS_process_vm_readv = 284,
    SYS_process_vm_writev = 285,
    SYS_kcmp = 286,
    SYS_finit_module = 287,
    SYS_sched_setattr = 288,
    SYS_sched_getattr = 289,
    SYS_renameat2 = 290,
    SYS_seccomp = 291,
    SYS_getrandom = 292,
    SYS_memfd_create = 293,
    SYS_kexec_file_load = 294,
    SYS_bpf = 295,
    SYS_execveat = 296,
    SYS_socketpair = 297,
    SYS_process_madvise = 298,
    SYS_fanotify_init = 299,
    SYS_fanotify_mark = 300,
    SYS_prlimit64 = 301,
    SYS_name_to_handle_at = 302,
    SYS_open_by_handle_at = 303,
    SYS_clock_adjtime = 304,
    SYS_syncfs = 305,
    SYS_sendmmsg = 306,
    SYS_setns = 307,
    SYS_getcpu = 308,
    SYS_process_vm_readv = 309,
    SYS_process_vm_writev = 310,
    SYS_kcmp = 311,
    SYS_finit_module = 312,
    SYS_sched_setattr = 313,
    SYS_sched_getattr = 314,
    SYS_renameat2 = 315,
    SYS_seccomp = 316,
    SYS_getrandom = 317,
    SYS_memfd_create = 318,
    SYS_kexec_file_load = 319,
    SYS_bpf = 320,
    SYS_execveat = 321,
    SYS_socketpair = 322,
    SYS_process_madvise = 323,
    SYS_fanotify_init = 324,
    SYS_fanotify_mark = 325,
    SYS_prlimit64 = 326,
    SYS_name_to_handle_at = 327,
    SYS_open_by_handle_at = 328,
    SYS_clock_adjtime = 329,
    SYS_syncfs = 330,
    SYS_sendmmsg = 331
};

// Define syscall names
static const char *syscall_names[SYSCALL_COUNT] = {
    [SYS_read] = "read",
    [SYS_write] = "write",
    [SYS_open] = "open",
    [SYS_close] = "close",
    [SYS_stat] = "stat",
    [SYS_fstat] = "fstat",
    [SYS_lstat] = "lstat",
    [SYS_poll] = "poll",
    [SYS_lseek] = "lseek",
    [SYS_mmap] = "mmap",
    [SYS_mprotect] = "mprotect",
    [SYS_munmap] = "munmap",
    [SYS_brk] = "brk",
    [SYS_rt_sigaction] = "rt_sigaction",
    [SYS_rt_sigprocmask] = "rt_sigprocmask",
    [SYS_rt_sigreturn] = "rt_sigreturn",
    [SYS_ioctl] = "ioctl",
    [SYS_pread64] = "pread64",
    [SYS_pwrite64] = "pwrite64",
    [SYS_readv] = "readv",
    [SYS_writev] = "writev",
    [SYS_access] = "access",
    [SYS_pipe] = "pipe",
    [SYS_select] = "select",
    [SYS_sched_yield] = "sched_yield",
    [SYS_mremap] = "mremap",
    [SYS_msync] = "msync",
    [SYS_mincore] = "mincore",
    [SYS_madvise] = "madvise",
    [SYS_shmget] = "shmget",
    [SYS_shmat] = "shmat",
    [SYS_shmctl] = "shmctl",
    [SYS_dup] = "dup",
    [SYS_dup2] = "dup2",
    [SYS_pause] = "pause",
    [SYS_nanosleep] = "nanosleep",
    [SYS_getitimer] = "getitimer",
    [SYS_alarm] = "alarm",
    [SYS_setitimer] = "setitimer",
    [SYS_getpid] = "getpid",
    [SYS_sendfile] = "sendfile",
    [SYS_socket] = "socket",
    [SYS_connect] = "connect",
    [SYS_accept] = "accept",
    [SYS_sendto] = "sendto",
    [SYS_recvfrom] = "recvfrom",
    [SYS_shutdown] = "shutdown",
    [SYS_bind] = "bind",
    [SYS_listen] = "listen",
    [SYS_getsockname] = "getsockname",
    [SYS_getpeername] = "getpeername",
    [SYS_socketpair] = "socketpair",
    [SYS_setsockopt] = "setsockopt",
    [SYS_getsockopt] = "getsockopt",
    [SYS_clone] = "clone",
    [SYS_fork] = "fork",
    [SYS_vfork] = "vfork",
    [SYS_execve] = "execve",
    [SYS_exit] = "exit",
    [SYS_wait4] = "wait4",
    [SYS_kill] = "kill",
    [SYS_uname] = "uname",
    [SYS_semget] = "semget",
    [SYS_semop] = "semop",
    [SYS_semctl] = "semctl",
    [SYS_shmdt] = "shmdt",
    [SYS_msgget] = "msgget",
    [SYS_msgsnd] = "msgsnd",
    [SYS_msgrcv] = "msgrcv",
    [SYS_msgctl] = "msgctl",
    [SYS_fcntl] = "fcntl",
    [SYS_flock] = "flock",
    [SYS_fsync] = "fsync",
    [SYS_fdatasync] = "fdatasync",
    [SYS_truncate] = "truncate",
    [SYS_ftruncate] = "ftruncate",
    [SYS_getdents] = "getdents",
    [SYS_getcwd] = "getcwd",
    [SYS_chdir] = "chdir",
    [SYS_fchdir] = "fchdir",
    [SYS_rename] = "rename",
    [SYS_mkdir] = "mkdir",
    [SYS_rmdir] = "rmdir",
    [SYS_creat] = "creat",
    [SYS_link] = "link",
    [SYS_unlink] = "unlink",
    [SYS_symlink] = "symlink",
    [SYS_readlink] = "readlink",
    [SYS_chmod] = "chmod",
    [SYS_fchmod] = "fchmod",
    [SYS_chown] = "chown",
    [SYS_fchown] = "fchown",
    [SYS_lchown] = "lchown",
    [SYS_umask] = "umask",
    [SYS_gettimeofday] = "gettimeofday",
    [SYS_getrlimit] = "getrlimit",
    [SYS_getrusage] = "getrusage",
    [SYS_sysinfo] = "sysinfo",
    [SYS_times] = "times",
    [SYS_ptrace] = "ptrace",
    [SYS_getuid] = "getuid",
    [SYS_syslog] = "syslog",
    [SYS_getgid] = "getgid",
    [SYS_setuid] = "setuid",
    [SYS_setgid] = "setgid",
    [SYS_geteuid] = "geteuid",
    [SYS_getegid] = "getegid",
    [SYS_setpgid] = "setpgid",
    [SYS_getppid] = "getppid",
    [SYS_getpgrp] = "getpgrp",
    [SYS_setsid] = "setsid",
    [SYS_setreuid] = "setreuid",
    [SYS_setregid] = "setregid",
    [SYS_getgroups] = "getgroups",
    [SYS_setgroups] = "setgroups",
    [SYS_setresuid] = "setresuid",
    [SYS_getresuid] = "getresuid",
    [SYS_setresgid] = "setresgid",
    [SYS_getresgid] = "getresgid",
    [SYS_getpgid] = "getpgid",
    [SYS_setfsuid] = "setfsuid",
    [SYS_setfsgid] = "setfsgid",
    [SYS_getsid] = "getsid",
    [SYS_capget] = "capget",
    [SYS_capset] = "capset",
    [SYS_rt_sigpending] = "rt_sigpending",
    [SYS_rt_sigtimedwait] = "rt_sigtimedwait",
    [SYS_rt_sigqueueinfo] = "rt_sigqueueinfo",
    [SYS_rt_sigsuspend] = "rt_sigsuspend",
    [SYS_sigaltstack] = "sigaltstack",
    [SYS_utime] = "utime",
    [SYS_mknod] = "mknod",
    [SYS_personality] = "personality",
    [SYS_ustat] = "ustat",
    [SYS_statfs] = "statfs",
    [SYS_fstatfs] = "fstatfs",
    [SYS_sysfs] = "sysfs",
    [SYS_getpriority] = "getpriority",
    [SYS_setpriority] = "setpriority",
    [SYS_sched_setparam] = "sched_setparam",
    [SYS_sched_getparam] = "sched_getparam",
    [SYS_sched_setscheduler] = "sched_setscheduler",
    [SYS_sched_getscheduler] = "sched_getscheduler",
    [SYS_sched_get_priority_max] = "sched_get_priority_max",
    [SYS_sched_get_priority_min] = "sched_get_priority_min",
    [SYS_sched_rr_get_interval] = "sched_rr_get_interval",
    [SYS_mlock] = "mlock",
    [SYS_munlock] = "munlock",
    [SYS_mlockall] = "mlockall",
    [SYS_munlockall] = "munlockall",
    [SYS_vhangup] = "vhangup",
    [SYS_modify_ldt] = "modify_ldt",
    [SYS_pivot_root] = "pivot_root",
    [SYS_sysctl] = "sysctl",
    [SYS_prctl] = "prctl",
    [SYS_arch_prctl] = "arch_prctl",
    [SYS_adjtimex] = "adjtimex",
    [SYS_setrlimit] = "setrlimit",
    [SYS_chroot] = "chroot",
    [SYS_sync] = "sync",
    [SYS_acct] = "acct",
    [SYS_settimeofday] = "settimeofday",
    [SYS_mount] = "mount",
    [SYS_umount2] = "umount2",
    [SYS_swapon] = "swapon",
    [SYS_swapoff] = "swapoff",
    [SYS_reboot] = "reboot",
    [SYS_sethostname] = "sethostname",
    [SYS_setdomainname] = "setdomainname",
    [SYS_iopl] = "iopl",
    [SYS_ioperm] = "ioperm",
    [SYS_create_module] = "create_module",
    [SYS_init_module] = "init_module",
    [SYS_delete_module] = "delete_module",
    [SYS_get_kernel_syms] = "get_kernel_syms",
    [SYS_query_module] = "query_module",
    [SYS_quotactl] = "quotactl",
    [SYS_nfsservctl] = "nfsservctl",
    [SYS_getpmsg] = "getpmsg",
    [SYS_putpmsg] = "putpmsg",
    [SYS_afs_syscall] = "afs_syscall",
    [SYS_tuxcall] = "tuxcall",
    [SYS_security] = "security",
    [SYS_gettid] = "gettid",
    [SYS_readahead] = "readahead",
    [SYS_setxattr] = "setxattr",
    [SYS_lsetxattr] = "lsetxattr",
    [SYS_fsetxattr] = "fsetxattr",
    [SYS_getxattr] = "getxattr",
    [SYS_lgetxattr] = "lgetxattr",
    [SYS_fgetxattr] = "fgetxattr",
    [SYS_listxattr] = "listxattr",
    [SYS_llistxattr] = "llistxattr",
    [SYS_flistxattr] = "flistxattr",
    [SYS_removexattr] = "removexattr",
    [SYS_lremovexattr] = "lremovexattr",
    [SYS_fremovexattr] = "fremovexattr",
    [SYS_tkill] = "tkill",
    [SYS_time] = "time",
    [SYS_futex] = "futex",
    [SYS_sched_setaffinity] = "sched_setaffinity",
    [SYS_sched_getaffinity] = "sched_getaffinity",
    [SYS_set_thread_area] = "set_thread_area",
    [SYS_get_thread_area] = "get_thread_area",
    [SYS_io_setup] = "io_setup",
    [SYS_io_destroy] = "io_destroy",
    [SYS_io_getevents] = "io_getevents",
    [SYS_io_submit] = "io_submit",
    [SYS_io_cancel] = "io_cancel",
    [SYS_fadvise64] = "fadvise64",
    [SYS_exit_group] = "exit_group",
    [SYS_lookup_dcookie] = "lookup_dcookie",
    [SYS_epoll_create] = "epoll_create",
    [SYS_epoll_ctl] = "epoll_ctl",
    [SYS_epoll_wait] = "epoll_wait",
    [SYS_remap_file_pages] = "remap_file_pages",
    [SYS_set_tid_address] = "set_tid_address",
    [SYS_timer_create] = "timer_create",
    [SYS_timer_settime] = "timer_settime",
    [SYS_timer_gettime] = "timer_gettime",
    [SYS_timer_getoverrun] = "timer_getoverrun",
    [SYS_timer_delete] = "timer_delete",
    [SYS_clock_settime] = "clock_settime",
    [SYS_clock_gettime] = "clock_gettime",
    [SYS_clock_getres] = "clock_getres",
    [SYS_clock_nanosleep] = "clock_nanosleep",
    [SYS_syslog] = "syslog",
    [SYS_ptrace] = "ptrace",
    [SYS_sched_setparam] = "sched_setparam",
    [SYS_sched_getparam] = "sched_getparam",
    [SYS_sched_setattr] = "sched_setattr",
    [SYS_sched_getattr] = "sched_getattr",
    [SYS_sched_yield] = "sched_yield",
    [SYS_sched_getscheduler] = "sched_getscheduler",
    [SYS_sched_get_priority_max] = "sched_get_priority_max",
    [SYS_sched_get_priority_min] = "sched_get_priority_min",
    [SYS_sched_rr_get_interval] = "sched_rr_get_interval",
    [SYS_pread64] = "pread64",
    [SYS_pwrite64] = "pwrite64",
    [SYS_preadv] = "preadv",
    [SYS_pwritev] = "pwritev",
    [SYS_fallocate] = "fallocate",
    [SYS_pselect6] = "pselect6",
    [SYS_ppoll] = "ppoll",
    [SYS_unshare] = "unshare",
    [SYS_set_robust_list] = "set_robust_list",
    [SYS_get_robust_list] = "get_robust_list",
    [SYS_splice] = "splice",
    [SYS_tee] = "tee",
    [SYS_sync_file_range] = "sync_file_range",
    [SYS_vmsplice] = "vmsplice",
    [SYS_move_pages] = "move_pages",
    [SYS_utimensat] = "utimensat",
    [SYS_epoll_pwait] = "epoll_pwait",
    [SYS_signalfd] = "signalfd",
    [SYS_timerfd_create] = "timerfd_create",
    [SYS_eventfd] = "eventfd",
    [SYS_fallocate] = "fallocate",
    [SYS_timerfd_settime] = "timerfd_settime",
    [SYS_timerfd_gettime] = "timerfd_gettime",
    [SYS_signalfd4] = "signalfd4",
    [SYS_eventfd2] = "eventfd2",
    [SYS_epoll_create1] = "epoll_create1",
    [SYS_dup3] = "dup3",
    [SYS_pipe2] = "pipe2",
    [SYS_inotify_init1] = "inotify_init1",
    [SYS_preadv2] = "preadv2",
    [SYS_pwritev2] = "pwritev2",
    [SYS_rt_tgsigqueueinfo] = "rt_tgsigqueueinfo",
    [SYS_perf_event_open] = "perf_event_open",
    [SYS_recvmmsg] = "recvmmsg",
    [SYS_fanotify_init] = "fanotify_init",
    [SYS_fanotify_mark] = "fanotify_mark",
    [SYS_prlimit64] = "prlimit64",
    [SYS_name_to_handle_at] = "name_to_handle_at",
    [SYS_open_by_handle_at] = "open_by_handle_at",
    [SYS_clock_adjtime] = "clock_adjtime",
    [SYS_syncfs] = "syncfs",
    [SYS_sendmmsg] = "sendmmsg",
    [SYS_setns] = "setns",
    [SYS_getcpu] = "getcpu",
    [SYS_process_vm_readv] = "process_vm_readv",
    [SYS_process_vm_writev] = "process_vm_writev",
    [SYS_kcmp] = "kcmp",
    [SYS_finit_module] = "finit_module",
    [SYS_sched_setattr] = "sched_setattr",
    [SYS_sched_getattr] = "sched_getattr",
    [SYS_renameat2] = "renameat2",
    [SYS_seccomp] = "seccomp",
    [SYS_getrandom] = "getrandom",
    [SYS_memfd_create] = "memfd_create",
    [SYS_kexec_file_load] = "kexec_file_load",
    [SYS_bpf] = "bpf",
    [SYS_execveat] = "execveat",
    [SYS_socketpair] = "socketpair",
    [SYS_process_madvise] = "process_madvise",
    [SYS_fanotify_init] = "fanotify_init",
    [SYS_fanotify_mark] = "fanotify_mark",
    [SYS_prlimit64] = "prlimit64",
    [SYS_name_to_handle_at] = "name_to_handle_at",
    [SYS_open_by_handle_at] = "open_by_handle_at",
    [SYS_clock_adjtime] = "clock_adjtime",
    [SYS_syncfs] = "syncfs",
    [SYS_sendmmsg] = "sendmmsg"
};


#endif /* !_SYSCALLS_H_ */
